// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platzi_ASP_NET_CORE.Models;

#nullable disable

namespace Platzi_ASP_NET_CORE.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20220525144815_independent")]
    partial class independent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = "014f2c08-4307-4331-9c8a-771e7a91ff73",
                            Nombre = "Donald Silvana Herrera"
                        },
                        new
                        {
                            Id = "01cb5738-45cb-460e-bb97-4588724c7436",
                            Nombre = "Felipa Freddy Uribe"
                        },
                        new
                        {
                            Id = "01d38d3f-b91e-4df6-a91a-7d0f3d7f2ddb",
                            Nombre = "Eusebio Murty Ruiz"
                        },
                        new
                        {
                            Id = "02328a29-b631-40c4-a237-c970bf8c566b",
                            Nombre = "Donald Murty Trump"
                        },
                        new
                        {
                            Id = "02d806a2-837a-4169-b722-74cd9736ded2",
                            Nombre = "Nicolás Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "02dda57d-9271-43da-8495-3e76ad03c445",
                            Nombre = "Eusebio Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "02e5ff0f-15fb-41d9-b405-8568afa17781",
                            Nombre = "Farid Rick Herrera"
                        },
                        new
                        {
                            Id = "0343f0e7-680e-4350-a735-89b68432d4c3",
                            Nombre = "Eusebio Diomedes Maduro"
                        },
                        new
                        {
                            Id = "0388e9d9-8651-41de-b8fb-e4290239f7c3",
                            Nombre = "Nicolás Rick Maduro"
                        },
                        new
                        {
                            Id = "059a9a23-4048-46a3-83a9-e83d72fc4176",
                            Nombre = "Alvaro Murty Uribe"
                        },
                        new
                        {
                            Id = "07acf5b8-b664-4471-b0eb-549c1247ee4f",
                            Nombre = "Nicolás Murty Sarmiento"
                        },
                        new
                        {
                            Id = "07d7662f-508c-4172-9aca-ef42e6c2dd68",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "086146fe-5525-479b-823b-d61a2bb232cc",
                            Nombre = "Felipa Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "08a5c13f-fb38-4a43-9fa4-19746265cabe",
                            Nombre = "Donald Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "08b82da6-9a9f-4ff5-9d34-6e879119929d",
                            Nombre = "Alvaro Diomedes Maduro"
                        },
                        new
                        {
                            Id = "096077f3-14e1-4789-a255-cf4a7bc0cd7d",
                            Nombre = "Felipa Silvana Maduro"
                        },
                        new
                        {
                            Id = "0abe3e23-941c-48bc-89c1-ca4465ba951a",
                            Nombre = "Nicolás Teodoro Maduro"
                        },
                        new
                        {
                            Id = "0d586482-3131-4b97-83b1-207a528099ca",
                            Nombre = "Felipa Anabel Herrera"
                        },
                        new
                        {
                            Id = "0deb31c8-8584-4770-9151-5939091a50ef",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "0df42ddb-8b0e-444d-8340-1b89ca6cf327",
                            Nombre = "Eusebio Diomedes Toledo"
                        },
                        new
                        {
                            Id = "0e0c11a3-4c30-4d6d-8d24-24dbee6129f0",
                            Nombre = "Alba Rick Trump"
                        },
                        new
                        {
                            Id = "0f6f34e1-1a97-497f-bb40-026e917fa127",
                            Nombre = "Alba Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "0fc702c4-e07f-4370-a019-129c1dfe0717",
                            Nombre = "Eusebio Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "100577da-caf1-4eee-8250-6f73f3c04723",
                            Nombre = "Farid Rick Toledo"
                        },
                        new
                        {
                            Id = "104da80d-e2cf-496e-8662-168682dc00b2",
                            Nombre = "Felipa Silvana Herrera"
                        },
                        new
                        {
                            Id = "109b17db-2659-4d48-b259-161dee16537c",
                            Nombre = "Alvaro Murty Trump"
                        },
                        new
                        {
                            Id = "11caf9e7-853b-4100-957b-d60b9da773a1",
                            Nombre = "Felipa Rick Toledo"
                        },
                        new
                        {
                            Id = "12f9a5f3-cf23-478b-9ac8-a315092ab501",
                            Nombre = "Farid Teodoro Toledo"
                        },
                        new
                        {
                            Id = "135a35b2-5e84-4b78-a09d-1fb5241e7b4b",
                            Nombre = "Farid Freddy Maduro"
                        },
                        new
                        {
                            Id = "142132b4-46ce-41d4-a33f-6af0935b8f3f",
                            Nombre = "Donald Rick Toledo"
                        },
                        new
                        {
                            Id = "1499ee8c-ee1e-429c-b572-5714742c2775",
                            Nombre = "Eusebio Anabel Herrera"
                        },
                        new
                        {
                            Id = "149b011c-f054-4e85-a1e4-472d26597a10",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "14a77ea1-8eda-4fa7-b2ca-113b2459dc3f",
                            Nombre = "Donald Murty Sarmiento"
                        },
                        new
                        {
                            Id = "14eb142a-4aff-487a-8bb2-7b28271fea81",
                            Nombre = "Donald Teodoro Maduro"
                        },
                        new
                        {
                            Id = "158ce168-6565-478a-a2f9-6ae978a1ff59",
                            Nombre = "Alvaro Silvana Maduro"
                        },
                        new
                        {
                            Id = "15c8caa3-1aad-42f7-98fc-bf66dd946de9",
                            Nombre = "Farid Silvana Maduro"
                        },
                        new
                        {
                            Id = "172f7162-25f0-435c-a0cd-b53b40a8a182",
                            Nombre = "Eusebio Murty Sarmiento"
                        },
                        new
                        {
                            Id = "180ad767-a054-4a9c-9099-1acded145eda",
                            Nombre = "Alvaro Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "185fd04e-45da-477e-894c-35ec61cf0045",
                            Nombre = "Alvaro Diomedes Toledo"
                        },
                        new
                        {
                            Id = "1900aa74-ef07-4036-8248-55322492c382",
                            Nombre = "Alvaro Nicomedes Trump"
                        },
                        new
                        {
                            Id = "190b760a-373c-410c-8ae4-10715451f9a7",
                            Nombre = "Farid Silvana Trump"
                        },
                        new
                        {
                            Id = "19d9480b-ab91-42d4-8db0-1cf0576df970",
                            Nombre = "Felipa Rick Trump"
                        },
                        new
                        {
                            Id = "1a3c036b-be9d-4aec-9926-7654b36e59ae",
                            Nombre = "Nicolás Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "1af67c42-7a16-4115-9e25-2788c7505502",
                            Nombre = "Farid Freddy Uribe"
                        },
                        new
                        {
                            Id = "1b0d6b25-ec14-41f0-9ee7-08c37d5cf627",
                            Nombre = "Eusebio Murty Maduro"
                        },
                        new
                        {
                            Id = "1ba21548-5392-475b-8064-1422361fa222",
                            Nombre = "Alba Freddy Maduro"
                        },
                        new
                        {
                            Id = "1c0cc94d-730b-4ddf-80f4-cc16cee9631f",
                            Nombre = "Alvaro Rick Herrera"
                        },
                        new
                        {
                            Id = "1d099ef1-f2ca-4270-af45-811f25e8dbf8",
                            Nombre = "Nicolás Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "1f4860bf-652a-4426-aa6c-678a05ecafef",
                            Nombre = "Eusebio Freddy Maduro"
                        },
                        new
                        {
                            Id = "1f4d8406-44ea-426d-9675-9125ad269157",
                            Nombre = "Alba Freddy Ruiz"
                        },
                        new
                        {
                            Id = "1fa0786e-eef6-4438-8541-84558aedd3a3",
                            Nombre = "Eusebio Nicomedes Trump"
                        },
                        new
                        {
                            Id = "1fafdb01-94bb-4853-a128-4989b5849124",
                            Nombre = "Alvaro Diomedes Herrera"
                        },
                        new
                        {
                            Id = "1fe629ff-28d9-4b1b-a118-155995fa3892",
                            Nombre = "Felipa Silvana Ruiz"
                        },
                        new
                        {
                            Id = "1ff8d546-f282-4afd-b181-29ba371b97ee",
                            Nombre = "Alba Anabel Trump"
                        },
                        new
                        {
                            Id = "208e69ca-7e41-44da-8e15-34fd9fcb60fc",
                            Nombre = "Alba Anabel Herrera"
                        },
                        new
                        {
                            Id = "2092ca07-1ca7-4bd8-8343-ad8479c69015",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "214c858a-d7dd-4606-832e-78f60bec719c",
                            Nombre = "Alvaro Rick Maduro"
                        },
                        new
                        {
                            Id = "244ed13b-9643-4f84-a8e6-c54d30220987",
                            Nombre = "Alba Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "2498d05e-e9e1-47ba-aed5-cf62fe155614",
                            Nombre = "Nicolás Freddy Maduro"
                        },
                        new
                        {
                            Id = "24f0112c-7298-4981-a968-8a5633635d07",
                            Nombre = "Nicolás Freddy Toledo"
                        },
                        new
                        {
                            Id = "25013ea0-2785-49af-b6eb-1add1ea1a26e",
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            Id = "2523d1dd-db76-4302-847f-5613c3946973",
                            Nombre = "Felipa Diomedes Trump"
                        },
                        new
                        {
                            Id = "26b42325-9ef0-4cfe-b2c0-4d72ccdbfd88",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "27ef5cfe-1f14-4e3e-b578-4cf920b738cb",
                            Nombre = "Felipa Anabel Toledo"
                        },
                        new
                        {
                            Id = "28f0bc72-c656-4d16-8368-8ff000a5ba69",
                            Nombre = "Felipa Murty Trump"
                        },
                        new
                        {
                            Id = "29d3a847-6e0e-4a1a-9150-59e850ce0a6e",
                            Nombre = "Farid Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "2b5960d2-c4f1-47e6-9813-2bc4c7a15c6a",
                            Nombre = "Alvaro Anabel Uribe"
                        },
                        new
                        {
                            Id = "2bb587c4-4db7-4b60-b73f-e865ba08f7a6",
                            Nombre = "Alba Murty Toledo"
                        },
                        new
                        {
                            Id = "2c29401d-0f8a-4ccb-85bb-5bbe4d087489",
                            Nombre = "Alba Freddy Toledo"
                        },
                        new
                        {
                            Id = "2c8f1807-3b2c-4dfd-a658-6ad66f04896a",
                            Nombre = "Alba Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "2d2b4b8d-92aa-44de-816f-f91354c6f750",
                            Nombre = "Nicolás Silvana Herrera"
                        },
                        new
                        {
                            Id = "2df582ba-d623-47e6-acd9-515786c81aca",
                            Nombre = "Farid Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "2e242f22-eb68-48c0-b613-97ee03a275f8",
                            Nombre = "Farid Teodoro Maduro"
                        },
                        new
                        {
                            Id = "2efdc03a-7baa-46af-9949-a78486acf027",
                            Nombre = "Farid Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "2f4be8c6-064f-4cd4-955a-c674a401ed44",
                            Nombre = "Alvaro Rick Uribe"
                        },
                        new
                        {
                            Id = "2f88a367-38b3-41ff-9b61-c53145a0c3a6",
                            Nombre = "Alba Diomedes Uribe"
                        },
                        new
                        {
                            Id = "2f8ecaef-b25a-4da4-a62b-cd3c7a40bd1e",
                            Nombre = "Nicolás Nicomedes Trump"
                        },
                        new
                        {
                            Id = "30427b85-1c1c-46e6-9c2d-4c7bf26b5316",
                            Nombre = "Alba Rick Sarmiento"
                        },
                        new
                        {
                            Id = "304bd886-bf8b-4399-a26b-bdcd3bd70130",
                            Nombre = "Donald Murty Herrera"
                        },
                        new
                        {
                            Id = "304d108d-0d57-4be6-8695-2c9225858b4d",
                            Nombre = "Alba Murty Sarmiento"
                        },
                        new
                        {
                            Id = "310bbae4-6ea6-46c0-b27b-fc495bb3b3c9",
                            Nombre = "Alba Anabel Toledo"
                        },
                        new
                        {
                            Id = "325eabe7-9084-40e7-9fa9-060fea195a14",
                            Nombre = "Donald Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "32de3add-01b8-4848-94fa-7d286f57f5a3",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "32e9e6f8-d2d7-43c2-b51f-c823af9e6caf",
                            Nombre = "Nicolás Teodoro Herrera"
                        },
                        new
                        {
                            Id = "3452f425-738a-4dde-912b-6c673f5632bf",
                            Nombre = "Farid Freddy Ruiz"
                        },
                        new
                        {
                            Id = "34878d9c-4df6-4773-9b28-e479ed7c6df0",
                            Nombre = "Felipa Silvana Toledo"
                        },
                        new
                        {
                            Id = "3498e08c-cd43-401e-b620-099333d9651b",
                            Nombre = "Nicolás Murty Maduro"
                        },
                        new
                        {
                            Id = "3613e759-bc8b-4ad4-a4ce-98cd815becf6",
                            Nombre = "Farid Rick Maduro"
                        },
                        new
                        {
                            Id = "3624d967-0b23-4bfd-9dc9-9b1049ea4782",
                            Nombre = "Farid Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "3684f667-2444-4518-9097-7a9b939b7214",
                            Nombre = "Donald Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "3729d36d-8d07-4738-a2a8-a92e7789e694",
                            Nombre = "Farid Teodoro Trump"
                        },
                        new
                        {
                            Id = "37de46ea-b831-4c9f-b685-da589a4e9db3",
                            Nombre = "Felipa Silvana Trump"
                        },
                        new
                        {
                            Id = "3a0999ce-e63f-446d-af83-9daa54d6b897",
                            Nombre = "Farid Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "3a1dafeb-872d-4196-844f-e2f4225f61d7",
                            Nombre = "Donald Silvana Maduro"
                        },
                        new
                        {
                            Id = "3aa46a23-445c-4eeb-b32e-a816cf17f71d",
                            Nombre = "Alba Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "3b29555d-17da-4319-9fc0-77fea66a977f",
                            Nombre = "Felipa Freddy Toledo"
                        },
                        new
                        {
                            Id = "3bbab54e-0d59-4ca1-a92d-db64c0de1a22",
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            Id = "3ceef899-ddca-423e-91ec-d0a1c8a7143a",
                            Nombre = "Eusebio Anabel Uribe"
                        },
                        new
                        {
                            Id = "3dd2201a-e688-4f92-b88e-d7a92cc0a05a",
                            Nombre = "Alvaro Murty Ruiz"
                        },
                        new
                        {
                            Id = "3dd250a5-8ccc-4953-9f34-60a86196fa86",
                            Nombre = "Felipa Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "3e08edd9-8029-48c0-b773-9526f2609491",
                            Nombre = "Donald Rick Trump"
                        },
                        new
                        {
                            Id = "3e86a4d4-ce05-42ce-ae15-f2054864771f",
                            Nombre = "Eusebio Rick Herrera"
                        },
                        new
                        {
                            Id = "3f30b286-524f-4d5a-b5c9-42a040180dc3",
                            Nombre = "Nicolás Murty Toledo"
                        },
                        new
                        {
                            Id = "3f8e87a0-9661-480b-b192-30728652cb1a",
                            Nombre = "Donald Teodoro Uribe"
                        },
                        new
                        {
                            Id = "3f95e074-0c7e-4f7a-aafd-28ddf126f2b4",
                            Nombre = "Alvaro Anabel Maduro"
                        },
                        new
                        {
                            Id = "402dc189-ccf9-45e9-a8d4-61c32245efd4",
                            Nombre = "Felipa Anabel Maduro"
                        },
                        new
                        {
                            Id = "41899b52-142d-43bf-b63c-083be606e6a3",
                            Nombre = "Alvaro Rick Sarmiento"
                        },
                        new
                        {
                            Id = "42453d56-aa03-4cfc-b47d-15a9868c53e9",
                            Nombre = "Donald Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "43a1def7-a066-4599-9ddf-5fc260655500",
                            Nombre = "Donald Rick Ruiz"
                        },
                        new
                        {
                            Id = "44c10fd4-4977-4c00-9a93-9223bf0076f8",
                            Nombre = "Alvaro Diomedes Uribe"
                        },
                        new
                        {
                            Id = "44f95290-b535-4f89-b80a-5f0af1b8d58c",
                            Nombre = "Farid Murty Sarmiento"
                        },
                        new
                        {
                            Id = "4668dae6-5d71-4faa-b6c0-1296b5ef8fe2",
                            Nombre = "Farid Rick Sarmiento"
                        },
                        new
                        {
                            Id = "46c094d4-0777-44e4-b3d9-1e8b7a483689",
                            Nombre = "Felipa Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "47e3fd17-03ca-481b-a5b5-29b193096b02",
                            Nombre = "Alvaro Rick Trump"
                        },
                        new
                        {
                            Id = "483fa752-4173-4f6d-908e-e6478b8b2b03",
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            Id = "485f68e1-7fec-49d3-88ca-4e4760892ae6",
                            Nombre = "Farid Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "493bbc62-bd30-4c24-bd59-c8341bf48e69",
                            Nombre = "Eusebio Rick Trump"
                        },
                        new
                        {
                            Id = "49854558-45a2-4058-8237-f5065f4bbd44",
                            Nombre = "Alba Murty Uribe"
                        },
                        new
                        {
                            Id = "4a026950-c64f-4b2e-a38c-38fb8f3b5bce",
                            Nombre = "Alba Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "4a05f0ae-127b-4e67-b50c-0ceb35191f36",
                            Nombre = "Farid Anabel Herrera"
                        },
                        new
                        {
                            Id = "4a2f4b5a-ad86-4c46-a265-4d0ebd548dbc",
                            Nombre = "Donald Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "4a83bd48-ea81-451f-a3da-facc9306e939",
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            Id = "4a9ab81b-3dd4-43c9-9b92-39062e9b54bd",
                            Nombre = "Alvaro Murty Maduro"
                        },
                        new
                        {
                            Id = "4bbfac8f-b1a3-4f27-a58d-98b02332d80a",
                            Nombre = "Alvaro Freddy Uribe"
                        },
                        new
                        {
                            Id = "4c3c225c-83ac-4c95-9563-5676750d407a",
                            Nombre = "Nicolás Murty Herrera"
                        },
                        new
                        {
                            Id = "4cb7e243-86c0-441c-bd04-a6f843eab956",
                            Nombre = "Eusebio Rick Ruiz"
                        },
                        new
                        {
                            Id = "4de1fa34-d89a-49e4-a45b-ed1bc1ef51de",
                            Nombre = "Alba Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "4e099933-00f9-4ebd-be68-1930fb484f0f",
                            Nombre = "Donald Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "4f91581c-4e07-4be4-b6bd-1ce60796b3fe",
                            Nombre = "Eusebio Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "50806ad9-b95b-4c7b-81e2-10197c2dc663",
                            Nombre = "Donald Rick Uribe"
                        },
                        new
                        {
                            Id = "51707cd6-6c8b-455e-882e-771c4b50ea40",
                            Nombre = "Felipa Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "52df7e09-1d48-4074-8dcd-46e3782258df",
                            Nombre = "Alba Murty Maduro"
                        },
                        new
                        {
                            Id = "54395b34-e144-4931-a4ad-5f35fca8da50",
                            Nombre = "Eusebio Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "5671e585-b3fe-4191-a1ef-62bf07e450c6",
                            Nombre = "Felipa Freddy Herrera"
                        },
                        new
                        {
                            Id = "56f0fe5c-fe2b-4f5c-a89a-460eb0f50821",
                            Nombre = "Felipa Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "574b25d9-6924-4452-8ab4-d77dd8cb956d",
                            Nombre = "Alvaro Murty Herrera"
                        },
                        new
                        {
                            Id = "57aacb3d-6184-45e7-9739-bf904d2443cf",
                            Nombre = "Alba Diomedes Trump"
                        },
                        new
                        {
                            Id = "57d80341-6ccb-43ca-ae6d-b86736a2fc04",
                            Nombre = "Farid Anabel Maduro"
                        },
                        new
                        {
                            Id = "58451afc-78bd-4463-b786-a526b2c4e396",
                            Nombre = "Alvaro Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "584f10bb-bc3c-45c8-aef4-4c72bb7a665c",
                            Nombre = "Eusebio Rick Uribe"
                        },
                        new
                        {
                            Id = "585e3f17-bc82-4c98-9c48-048bf8cb7fb3",
                            Nombre = "Farid Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "5881c211-a120-469c-9acf-bc0cd21198b2",
                            Nombre = "Nicolás Rick Uribe"
                        },
                        new
                        {
                            Id = "588338f8-5e14-4c0b-9f08-df9dd672a16f",
                            Nombre = "Felipa Teodoro Uribe"
                        },
                        new
                        {
                            Id = "58fcad1a-1828-4383-8c44-d68f181fc5a3",
                            Nombre = "Nicolás Anabel Trump"
                        },
                        new
                        {
                            Id = "59963058-ad50-405f-8f41-f022a8cfd4b5",
                            Nombre = "Donald Rick Herrera"
                        },
                        new
                        {
                            Id = "59bea895-ab0c-4105-b766-df9a220ebc1b",
                            Nombre = "Eusebio Diomedes Uribe"
                        },
                        new
                        {
                            Id = "59e95402-9029-44c6-b57e-0dca39712fd6",
                            Nombre = "Nicolás Silvana Toledo"
                        },
                        new
                        {
                            Id = "5aab94cb-1c48-46ee-a111-f736a0dac3cb",
                            Nombre = "Alvaro Teodoro Toledo"
                        },
                        new
                        {
                            Id = "5ae46881-1fe8-4ca7-957a-06519d4a585b",
                            Nombre = "Donald Murty Toledo"
                        },
                        new
                        {
                            Id = "5af19ffc-bf4c-483a-ba87-993169cc235c",
                            Nombre = "Eusebio Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "5c022454-7027-45a8-9ead-9e32116d95d3",
                            Nombre = "Nicolás Silvana Trump"
                        },
                        new
                        {
                            Id = "5cbefc1d-37c3-4932-9d32-5fbf2e9aad86",
                            Nombre = "Felipa Freddy Maduro"
                        },
                        new
                        {
                            Id = "5d2eeae4-e8e1-4956-ac92-a633d27d384b",
                            Nombre = "Farid Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "5d3f078e-d904-452d-b40e-193c08223746",
                            Nombre = "Donald Silvana Trump"
                        },
                        new
                        {
                            Id = "5fa44cc6-4220-4923-9db7-59e918aac018",
                            Nombre = "Alvaro Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "5fc32c09-fbfe-4e67-9724-8181e2d548c7",
                            Nombre = "Nicolás Freddy Herrera"
                        },
                        new
                        {
                            Id = "60c48e98-59b3-4d3c-8bbc-8f2306f27d31",
                            Nombre = "Farid Silvana Uribe"
                        },
                        new
                        {
                            Id = "60d51fb8-d6a2-4cf6-ac5c-be58d33d3a04",
                            Nombre = "Nicolás Anabel Toledo"
                        },
                        new
                        {
                            Id = "638ecc30-a7b0-4223-b66f-7e98b4599805",
                            Nombre = "Nicolás Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "6393074a-5889-499c-b0be-764f1b9a9092",
                            Nombre = "Donald Teodoro Herrera"
                        },
                        new
                        {
                            Id = "63d14665-7d7b-4da8-9249-b01d8f12f3e8",
                            Nombre = "Farid Anabel Trump"
                        },
                        new
                        {
                            Id = "6403c04c-f37d-4a04-80cb-f939260b3964",
                            Nombre = "Nicolás Teodoro Trump"
                        },
                        new
                        {
                            Id = "641fae4d-90bb-4487-b624-32fee3939dcc",
                            Nombre = "Felipa Murty Herrera"
                        },
                        new
                        {
                            Id = "659357d5-0a55-4a51-93f9-af84688f70da",
                            Nombre = "Felipa Diomedes Uribe"
                        },
                        new
                        {
                            Id = "65b2dc5f-82e5-4506-895d-db5ffd61c31b",
                            Nombre = "Alba Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "664e578a-47ad-4d58-b299-d3eba4c3f28f",
                            Nombre = "Alvaro Diomedes Trump"
                        },
                        new
                        {
                            Id = "66bc1933-5ac3-4c51-93ec-bb88ab87d1c0",
                            Nombre = "Donald Rick Maduro"
                        },
                        new
                        {
                            Id = "67279a92-4de6-4083-9904-8e3b53a6030c",
                            Nombre = "Alvaro Anabel Ruiz"
                        },
                        new
                        {
                            Id = "698e8a50-fb88-419a-a5db-9b317ccfe6d2",
                            Nombre = "Alba Anabel Ruiz"
                        },
                        new
                        {
                            Id = "69b1b110-6d25-47db-be5a-24f208c825cd",
                            Nombre = "Nicolás Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "69e6d0fa-bb2e-43a7-9626-f4a6d7ebdbbb",
                            Nombre = "Eusebio Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "6c7e1b43-09aa-48fd-ad3e-879129fa3ead",
                            Nombre = "Alvaro Freddy Trump"
                        },
                        new
                        {
                            Id = "6d62fc65-3467-4125-ac2d-1a37bb33808e",
                            Nombre = "Farid Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "6db0b4fd-28b3-451d-bd72-cd4acaf0c7fa",
                            Nombre = "Nicolás Rick Ruiz"
                        },
                        new
                        {
                            Id = "6e2b5a1d-3f12-4656-a8bb-4e849f2b9dc6",
                            Nombre = "Nicolás Silvana Ruiz"
                        },
                        new
                        {
                            Id = "6f14d4f4-018b-4242-b7d9-73e6cea1326b",
                            Nombre = "Alvaro Freddy Ruiz"
                        },
                        new
                        {
                            Id = "6f4afddd-1e17-4877-8fed-1c1fd4ddf46c",
                            Nombre = "Alvaro Rick Toledo"
                        },
                        new
                        {
                            Id = "6f7a7972-a430-4a05-9bf4-c70b6b2a7308",
                            Nombre = "Felipa Rick Sarmiento"
                        },
                        new
                        {
                            Id = "70da6c09-52c4-4b2f-a045-4b31dba1fe1c",
                            Nombre = "Nicolás Diomedes Herrera"
                        },
                        new
                        {
                            Id = "714cc615-992b-492d-8a37-976378068a00",
                            Nombre = "Alvaro Murty Toledo"
                        },
                        new
                        {
                            Id = "71b08e69-f468-4829-ad77-ed5398238bc6",
                            Nombre = "Felipa Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "721febcc-1ff4-42db-bbf4-26ed85263222",
                            Nombre = "Eusebio Anabel Ruiz"
                        },
                        new
                        {
                            Id = "7281e828-281d-470b-aede-6a85c67ec624",
                            Nombre = "Farid Diomedes Uribe"
                        },
                        new
                        {
                            Id = "73acc3f2-ee4e-4298-8121-607f8568ab06",
                            Nombre = "Farid Teodoro Uribe"
                        },
                        new
                        {
                            Id = "744f753a-2099-475a-87d8-84732e1a9123",
                            Nombre = "Farid Diomedes Maduro"
                        },
                        new
                        {
                            Id = "763c02cd-20bb-4f17-ab23-801470e197d8",
                            Nombre = "Eusebio Silvana Uribe"
                        },
                        new
                        {
                            Id = "769f0de9-8eff-43cf-b57c-5fecc347591c",
                            Nombre = "Alba Murty Herrera"
                        },
                        new
                        {
                            Id = "77b96a5a-3573-4c9d-b375-f6918b6a8758",
                            Nombre = "Alba Freddy Trump"
                        },
                        new
                        {
                            Id = "77dcea3e-7c6b-4f41-a768-1fc91b448e5f",
                            Nombre = "Nicolás Anabel Maduro"
                        },
                        new
                        {
                            Id = "79b350af-b41c-408d-bf4b-1ccbd5b8b926",
                            Nombre = "Alvaro Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "79cc71df-fc42-4d23-974d-e650074c9fb8",
                            Nombre = "Eusebio Diomedes Herrera"
                        },
                        new
                        {
                            Id = "7a563d7f-7941-4d28-ac7f-c352f25e7b73",
                            Nombre = "Alba Anabel Uribe"
                        },
                        new
                        {
                            Id = "7a82b92d-e346-44eb-a88c-c7988fde2890",
                            Nombre = "Donald Freddy Ruiz"
                        },
                        new
                        {
                            Id = "7b47870d-f0b4-47ec-93a6-eba29f30a273",
                            Nombre = "Alvaro Freddy Herrera"
                        },
                        new
                        {
                            Id = "7b7e6fc4-8876-4df4-af2e-9c7e7a38afe9",
                            Nombre = "Alba Nicomedes Trump"
                        },
                        new
                        {
                            Id = "7c091dee-9957-4e81-bbd7-257078268ccb",
                            Nombre = "Felipa Rick Uribe"
                        },
                        new
                        {
                            Id = "7d24014b-89e1-45cc-bbc8-2f2fbfba6066",
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "7df22418-707f-42cf-8c21-a560f334d1b9",
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            Id = "7e23fb36-bc8c-4d86-9951-af9ae29a4062",
                            Nombre = "Felipa Anabel Trump"
                        },
                        new
                        {
                            Id = "7e47cdde-11f4-4928-b51a-36a897eb694d",
                            Nombre = "Nicolás Murty Trump"
                        },
                        new
                        {
                            Id = "80867e44-fb75-47be-a196-035f5a72d6aa",
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            Id = "81139551-e4e8-41ea-b197-c053ce69db41",
                            Nombre = "Farid Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "819c8880-f02c-436a-be01-44e6626fb21a",
                            Nombre = "Eusebio Freddy Toledo"
                        },
                        new
                        {
                            Id = "82dbc3d4-ea0c-452b-b89a-fdc43bff76b7",
                            Nombre = "Alvaro Silvana Herrera"
                        },
                        new
                        {
                            Id = "8328025f-9775-47b4-988f-f9f9bd7a9189",
                            Nombre = "Donald Silvana Toledo"
                        },
                        new
                        {
                            Id = "834a0fe3-6928-4598-8fed-b4438e8bf907",
                            Nombre = "Donald Teodoro Toledo"
                        },
                        new
                        {
                            Id = "8398ebcd-371e-4561-9371-a5b1d471cf47",
                            Nombre = "Alba Teodoro Toledo"
                        },
                        new
                        {
                            Id = "848e423a-fc52-4f97-80fa-51feecde7467",
                            Nombre = "Felipa Freddy Ruiz"
                        },
                        new
                        {
                            Id = "8519f6ea-8bec-49fc-acb6-80f77792c83f",
                            Nombre = "Nicolás Teodoro Uribe"
                        },
                        new
                        {
                            Id = "85482bac-6eae-48ca-9eb2-210c79773dcd",
                            Nombre = "Alvaro Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "854e9e0c-c7cd-490a-81cb-b0986e3762c6",
                            Nombre = "Farid Rick Uribe"
                        },
                        new
                        {
                            Id = "85a0be86-9dd6-4a91-adf5-8878a56b8966",
                            Nombre = "Farid Freddy Toledo"
                        },
                        new
                        {
                            Id = "8672c4d0-d0d2-4958-9906-3a3f764ce76f",
                            Nombre = "Eusebio Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "8686e4af-e3ac-4c01-9ff9-a2b0ac9a79db",
                            Nombre = "Alba Rick Toledo"
                        },
                        new
                        {
                            Id = "88c47012-f04a-497e-9ff4-5e83df12a258",
                            Nombre = "Felipa Diomedes Toledo"
                        },
                        new
                        {
                            Id = "8ac5f4bf-9069-4358-849a-02701449964e",
                            Nombre = "Farid Diomedes Toledo"
                        },
                        new
                        {
                            Id = "8ae663db-aac1-47c4-a1ba-5ddc628838ff",
                            Nombre = "Nicolás Anabel Ruiz"
                        },
                        new
                        {
                            Id = "8b023d5e-2e80-4b64-ae0d-2cba245b31d2",
                            Nombre = "Farid Murty Herrera"
                        },
                        new
                        {
                            Id = "8b411fd7-ca9d-47e7-95b2-d620f379ec86",
                            Nombre = "Donald Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "8ba31376-4b05-42c6-af59-5d9566c07309",
                            Nombre = "Alba Teodoro Maduro"
                        },
                        new
                        {
                            Id = "8bac6ea2-1b35-4af0-9bba-7ec6512e35d6",
                            Nombre = "Nicolás Anabel Herrera"
                        },
                        new
                        {
                            Id = "8d102003-0e0f-4447-92d0-04dcc797f848",
                            Nombre = "Alvaro Teodoro Trump"
                        },
                        new
                        {
                            Id = "8d130951-4290-4287-b28e-d170e562a451",
                            Nombre = "Nicolás Diomedes Uribe"
                        },
                        new
                        {
                            Id = "8d8adcf5-c142-4fa3-96cc-143e0aea5aae",
                            Nombre = "Eusebio Silvana Maduro"
                        },
                        new
                        {
                            Id = "8d98f7b2-2729-4375-807e-1065d1fdfc7e",
                            Nombre = "Donald Silvana Uribe"
                        },
                        new
                        {
                            Id = "8db2c21c-0b5d-475a-b8df-c2e09b223fac",
                            Nombre = "Felipa Anabel Uribe"
                        },
                        new
                        {
                            Id = "8e3e9b12-b0bb-4d62-8e45-fc45c7021386",
                            Nombre = "Donald Anabel Herrera"
                        },
                        new
                        {
                            Id = "8ec894e2-69ce-45fe-a339-3ca3c9ce38bf",
                            Nombre = "Felipa Rick Ruiz"
                        },
                        new
                        {
                            Id = "8ef8c220-ec7d-4af4-ba08-799e8eae6735",
                            Nombre = "Donald Diomedes Maduro"
                        },
                        new
                        {
                            Id = "9031e096-61a7-458b-96f5-429811ea43cf",
                            Nombre = "Donald Freddy Uribe"
                        },
                        new
                        {
                            Id = "90529b22-ccdf-4ff3-bfd9-378bf164bd94",
                            Nombre = "Donald Anabel Maduro"
                        },
                        new
                        {
                            Id = "90e76397-5cd9-4178-b332-803936258d1d",
                            Nombre = "Donald Freddy Herrera"
                        },
                        new
                        {
                            Id = "914a6b1a-540b-4ba5-9c62-1e9afdae5fe3",
                            Nombre = "Alba Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "91b1e4e3-bcb8-475f-b6e7-d50814cc9d5d",
                            Nombre = "Farid Murty Trump"
                        },
                        new
                        {
                            Id = "927a358c-890e-425f-afbf-a0c25f69d68c",
                            Nombre = "Nicolás Freddy Trump"
                        },
                        new
                        {
                            Id = "928c0f38-aa11-4439-a33c-057ba4e28133",
                            Nombre = "Eusebio Teodoro Uribe"
                        },
                        new
                        {
                            Id = "9345c1c9-d462-430e-ae57-a11fa1ad1858",
                            Nombre = "Alba Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "9526a5c6-3b77-437a-86e9-2ee1c5b353fd",
                            Nombre = "Alba Silvana Herrera"
                        },
                        new
                        {
                            Id = "9551175d-df58-4741-98ac-58ac409446ab",
                            Nombre = "Donald Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "95cac5ae-d16f-4043-9362-db43d3610688",
                            Nombre = "Donald Nicomedes Trump"
                        },
                        new
                        {
                            Id = "96cfa176-1126-4fdc-ad2e-8f49f8243b95",
                            Nombre = "Alba Rick Uribe"
                        },
                        new
                        {
                            Id = "970daa3e-9268-4894-8bbc-ec16c8c06d8b",
                            Nombre = "Eusebio Silvana Herrera"
                        },
                        new
                        {
                            Id = "974547a9-7dd8-4988-8500-35f5d3e71eca",
                            Nombre = "Farid Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "984f2797-298a-474e-a9b1-f83014588e90",
                            Nombre = "Felipa Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "98f434e7-d359-4930-aa61-be54919ab649",
                            Nombre = "Alba Silvana Ruiz"
                        },
                        new
                        {
                            Id = "9926b28c-53b2-4fd4-9fa7-171834ddf597",
                            Nombre = "Nicolás Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "9a4d4395-97a8-4e2e-a1ef-4410059b6e77",
                            Nombre = "Alba Teodoro Uribe"
                        },
                        new
                        {
                            Id = "9b473f68-44fd-41f2-97bb-ef5a9049baa6",
                            Nombre = "Alba Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "9b7617e9-6d25-41f4-a028-f218adc487c6",
                            Nombre = "Alvaro Silvana Uribe"
                        },
                        new
                        {
                            Id = "9b91f947-f594-4278-b2b3-ac4104fe81d8",
                            Nombre = "Eusebio Teodoro Maduro"
                        },
                        new
                        {
                            Id = "9c520b31-bfa7-411b-aca3-10a56f828579",
                            Nombre = "Farid Rick Ruiz"
                        },
                        new
                        {
                            Id = "9c5eb086-4e15-403d-b5a9-e8d8041e0f11",
                            Nombre = "Nicolás Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "9cf9ee31-1e48-4f45-823d-8f4d7ef966de",
                            Nombre = "Donald Diomedes Herrera"
                        },
                        new
                        {
                            Id = "9d71cc6e-d104-4c9b-9293-666b97a5c8de",
                            Nombre = "Felipa Anabel Ruiz"
                        },
                        new
                        {
                            Id = "9da2fc1c-6c90-4d14-b1ac-2078f3cb4530",
                            Nombre = "Eusebio Murty Herrera"
                        },
                        new
                        {
                            Id = "9dc520a3-252b-446a-b6c5-cb6200506fb3",
                            Nombre = "Alba Anabel Maduro"
                        },
                        new
                        {
                            Id = "9e677d8a-b57b-498e-a62e-d03048d0c676",
                            Nombre = "Eusebio Silvana Ruiz"
                        },
                        new
                        {
                            Id = "9f5846a7-8f75-4d47-8591-e1809ee49c7f",
                            Nombre = "Nicolás Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "a0a7a2af-1f67-4ecf-82b4-fc08f2f28183",
                            Nombre = "Donald Rick Sarmiento"
                        },
                        new
                        {
                            Id = "a18995ed-44ba-43f6-9f56-3a9ea5515ba0",
                            Nombre = "Eusebio Silvana Trump"
                        },
                        new
                        {
                            Id = "a1d1a2ca-0f06-468e-823e-95442e2bd698",
                            Nombre = "Alvaro Freddy Toledo"
                        },
                        new
                        {
                            Id = "a24b680e-31ef-4a34-8d16-ce5fe220d727",
                            Nombre = "Eusebio Anabel Toledo"
                        },
                        new
                        {
                            Id = "a309ceda-9264-4a84-8a32-7251269fbeca",
                            Nombre = "Felipa Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "a3e2a4f7-ccbf-4c2d-af3d-27c6b74bc6be",
                            Nombre = "Alvaro Silvana Toledo"
                        },
                        new
                        {
                            Id = "a567a5ec-bff4-4ba8-a292-261a765c3ecb",
                            Nombre = "Felipa Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "a627f769-08a3-4334-b40b-85ef17685e6e",
                            Nombre = "Felipa Murty Toledo"
                        },
                        new
                        {
                            Id = "a81c32a3-6e0a-41ad-b800-da898f0ee92a",
                            Nombre = "Felipa Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "aa8ebb9b-31df-4c69-a0e9-75b1b8ba9720",
                            Nombre = "Alvaro Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "aabf502f-98f8-421d-8737-0e5f36dc6e05",
                            Nombre = "Alba Freddy Uribe"
                        },
                        new
                        {
                            Id = "ab5f980d-9366-4bbc-a679-f9fb7d7b4a98",
                            Nombre = "Nicolás Teodoro Toledo"
                        },
                        new
                        {
                            Id = "aba7fda5-d957-4024-87c7-34d079fac0c3",
                            Nombre = "Eusebio Freddy Ruiz"
                        },
                        new
                        {
                            Id = "abcde778-eb6d-41ec-b6fb-a1f39ab4266c",
                            Nombre = "Nicolás Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "aca84c35-721a-4590-a236-b3a9291d9076",
                            Nombre = "Nicolás Diomedes Trump"
                        },
                        new
                        {
                            Id = "acbf74fe-388d-4516-b297-d9bbe64ad308",
                            Nombre = "Farid Nicomedes Trump"
                        },
                        new
                        {
                            Id = "acd9272e-611c-4da5-8cfe-2bb2961880c5",
                            Nombre = "Donald Diomedes Uribe"
                        },
                        new
                        {
                            Id = "ad7197bf-3c99-4d76-9b4a-391e7cfec85d",
                            Nombre = "Alba Silvana Uribe"
                        },
                        new
                        {
                            Id = "ae79ceed-6338-480f-95cc-ab2bbfe0f31a",
                            Nombre = "Farid Rick Trump"
                        },
                        new
                        {
                            Id = "aed310a2-51bd-49c9-8b95-742f20c8b0ca",
                            Nombre = "Farid Murty Uribe"
                        },
                        new
                        {
                            Id = "af29c053-2e83-40f1-86b2-394e7b29a659",
                            Nombre = "Farid Silvana Toledo"
                        },
                        new
                        {
                            Id = "af3d069b-61c6-416e-b732-acabe7e10dfd",
                            Nombre = "Donald Freddy Maduro"
                        },
                        new
                        {
                            Id = "b061fe8d-f522-46f8-a4b5-542f3ac96819",
                            Nombre = "Alba Teodoro Herrera"
                        },
                        new
                        {
                            Id = "b09946e9-80ac-44fa-b23e-7774df544eaf",
                            Nombre = "Eusebio Teodoro Trump"
                        },
                        new
                        {
                            Id = "b0f14ae8-1426-4eb2-b905-3922177d19a5",
                            Nombre = "Nicolás Diomedes Maduro"
                        },
                        new
                        {
                            Id = "b1197635-bf27-4577-baaa-10119d1790e9",
                            Nombre = "Donald Diomedes Trump"
                        },
                        new
                        {
                            Id = "b11a545d-09e2-475a-8bea-3b032e521c6c",
                            Nombre = "Alvaro Murty Sarmiento"
                        },
                        new
                        {
                            Id = "b28d537d-c8ae-44fe-b233-38d332ad9772",
                            Nombre = "Donald Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "b39358d1-c4ea-461a-bfee-b86543e8bde5",
                            Nombre = "Alvaro Anabel Herrera"
                        },
                        new
                        {
                            Id = "b5689d28-d60f-46de-a27b-8c3c5d2cf869",
                            Nombre = "Eusebio Rick Toledo"
                        },
                        new
                        {
                            Id = "b5e7d607-a185-4665-b46e-efb3e81b51f5",
                            Nombre = "Eusebio Freddy Trump"
                        },
                        new
                        {
                            Id = "b6223971-8f95-49af-abdc-9f58abc43fa5",
                            Nombre = "Nicolás Rick Trump"
                        },
                        new
                        {
                            Id = "b637fc67-d3c2-4fa6-86e0-5d82cb0148df",
                            Nombre = "Eusebio Diomedes Trump"
                        },
                        new
                        {
                            Id = "b7446db6-5f76-4d95-8796-f234f44ba0f2",
                            Nombre = "Alvaro Silvana Ruiz"
                        },
                        new
                        {
                            Id = "b74df0d6-fcf9-40d9-9b67-49261d210e37",
                            Nombre = "Alba Silvana Maduro"
                        },
                        new
                        {
                            Id = "b7a32d86-9ebc-4730-ab26-d2a85194ed52",
                            Nombre = "Felipa Murty Maduro"
                        },
                        new
                        {
                            Id = "b8c0635a-7ca4-4102-a858-240ed2e6da08",
                            Nombre = "Farid Anabel Ruiz"
                        },
                        new
                        {
                            Id = "b93b433e-87f1-4d6f-9773-2dd7c34743e7",
                            Nombre = "Felipa Diomedes Maduro"
                        },
                        new
                        {
                            Id = "b9565db2-01fa-4f7a-b399-d1fa571b8319",
                            Nombre = "Eusebio Freddy Uribe"
                        },
                        new
                        {
                            Id = "bafd2c7a-0c76-45ab-901d-eaed2f62c7f4",
                            Nombre = "Felipa Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "bdb03449-2ce7-4474-9d4b-4666b8b6dd0f",
                            Nombre = "Eusebio Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "be258f9c-2ebe-42bc-9c3f-f8975581a7e1",
                            Nombre = "Eusebio Murty Uribe"
                        },
                        new
                        {
                            Id = "bf38858f-aead-41f5-93fa-b65937054743",
                            Nombre = "Eusebio Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "bfbc7563-afa8-4f80-96b5-3295c53c328f",
                            Nombre = "Nicolás Anabel Uribe"
                        },
                        new
                        {
                            Id = "c124bc1a-3bac-436f-89f2-fdb5d8ce3609",
                            Nombre = "Alba Rick Ruiz"
                        },
                        new
                        {
                            Id = "c3acab91-e6d6-4220-a92e-cf276d44fa5b",
                            Nombre = "Nicolás Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "c3bd216b-dfa1-479a-809e-e19694d3c868",
                            Nombre = "Alba Diomedes Toledo"
                        },
                        new
                        {
                            Id = "c69aacfe-dacf-4a26-acac-f997e1fcec86",
                            Nombre = "Nicolás Diomedes Toledo"
                        },
                        new
                        {
                            Id = "c74695e9-576d-4021-8731-020f40f5f0e3",
                            Nombre = "Nicolás Silvana Maduro"
                        },
                        new
                        {
                            Id = "c85d1bd0-46dc-49c2-ad14-0f74f24b56fe",
                            Nombre = "Eusebio Anabel Maduro"
                        },
                        new
                        {
                            Id = "c88802a3-7831-4df5-9cce-5c2b2cde3a8f",
                            Nombre = "Alba Silvana Trump"
                        },
                        new
                        {
                            Id = "c94ec83f-b259-40f5-b876-e8aaeec1b166",
                            Nombre = "Eusebio Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "c9b7876c-93df-4a9d-902f-bfbba3249dd1",
                            Nombre = "Alba Diomedes Herrera"
                        },
                        new
                        {
                            Id = "ca8b0bf9-e3cd-4ac0-b0e7-f1016ca0a727",
                            Nombre = "Eusebio Freddy Herrera"
                        },
                        new
                        {
                            Id = "cadc1597-4086-4132-b96d-6f7be2c5a7fe",
                            Nombre = "Alvaro Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "caf6e1d5-c658-4c11-ac7d-6c57c69f1977",
                            Nombre = "Nicolás Murty Uribe"
                        },
                        new
                        {
                            Id = "cb41a8a5-df0d-4695-9a08-588d38a42a39",
                            Nombre = "Alba Freddy Herrera"
                        },
                        new
                        {
                            Id = "cba95312-0215-4b75-9e01-c3c538205bb1",
                            Nombre = "Alvaro Teodoro Maduro"
                        },
                        new
                        {
                            Id = "cc1f39d0-992b-4fd4-b8b3-324d8cbc49eb",
                            Nombre = "Donald Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "cc338d66-37a6-4a47-91aa-32240958cf6a",
                            Nombre = "Alvaro Teodoro Uribe"
                        },
                        new
                        {
                            Id = "cc47c5a8-dec1-4a56-88af-a127b1476b58",
                            Nombre = "Nicolás Rick Herrera"
                        },
                        new
                        {
                            Id = "cd835ee5-5ac8-4d51-b020-bbb1e169acd4",
                            Nombre = "Farid Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "cdbee9e0-ecb0-441e-b97a-f6acede12492",
                            Nombre = "Donald Anabel Ruiz"
                        },
                        new
                        {
                            Id = "cdd10cad-02ba-4626-b037-2e18ec4549ac",
                            Nombre = "Donald Anabel Trump"
                        },
                        new
                        {
                            Id = "cdd12a5f-7477-4c6f-b3b7-32e7cf5cefd0",
                            Nombre = "Donald Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "cf82b975-3f8b-40b4-9ddf-057f16f0abb2",
                            Nombre = "Felipa Freddy Trump"
                        },
                        new
                        {
                            Id = "d1f3f997-6581-471e-80eb-99b17a149fd8",
                            Nombre = "Donald Murty Maduro"
                        },
                        new
                        {
                            Id = "d30f12f5-4c28-4020-9f02-7e2185b9993d",
                            Nombre = "Alba Diomedes Maduro"
                        },
                        new
                        {
                            Id = "d3124699-b8a8-42b4-afd2-66a64f60e59e",
                            Nombre = "Nicolás Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "d3d5bd0b-8ad9-45a2-8a66-fb068625a193",
                            Nombre = "Alvaro Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "d421d228-f6ab-4c33-b2c5-4bf0e23ff74c",
                            Nombre = "Alvaro Silvana Trump"
                        },
                        new
                        {
                            Id = "d43b1a7a-b45b-4503-b9b7-8238dc5e5e33",
                            Nombre = "Felipa Murty Uribe"
                        },
                        new
                        {
                            Id = "d4559d36-536e-48ca-857f-133a9320c61c",
                            Nombre = "Alvaro Rick Ruiz"
                        },
                        new
                        {
                            Id = "d477c5dc-5c93-485d-bb0a-d1097f002a0c",
                            Nombre = "Donald Freddy Trump"
                        },
                        new
                        {
                            Id = "d4a4d6c1-9e30-4a4b-b91d-e5427278737a",
                            Nombre = "Alba Rick Maduro"
                        },
                        new
                        {
                            Id = "d4de7946-96e2-4421-8ea8-617cb0a82d29",
                            Nombre = "Eusebio Rick Sarmiento"
                        },
                        new
                        {
                            Id = "d58279d7-66bd-4819-8489-da13a35c0ec4",
                            Nombre = "Nicolás Freddy Ruiz"
                        },
                        new
                        {
                            Id = "d5d7aa0d-6e74-476e-82ab-168a2e3f22b6",
                            Nombre = "Felipa Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "d5dcd568-8ef2-4bad-9060-82481ed35646",
                            Nombre = "Felipa Diomedes Herrera"
                        },
                        new
                        {
                            Id = "d6155f04-03f1-4028-906f-f91622d7df99",
                            Nombre = "Alba Rick Herrera"
                        },
                        new
                        {
                            Id = "d66cebe9-b387-497e-aea1-c5e1ac40350b",
                            Nombre = "Nicolás Murty Ruiz"
                        },
                        new
                        {
                            Id = "d6c12662-d261-47d8-a888-54493544cfb6",
                            Nombre = "Felipa Teodoro Trump"
                        },
                        new
                        {
                            Id = "d7479b60-8084-4425-95da-672669bd8870",
                            Nombre = "Donald Anabel Uribe"
                        },
                        new
                        {
                            Id = "d757323e-2458-46c2-9224-1a5b5dcd9ebf",
                            Nombre = "Farid Diomedes Trump"
                        },
                        new
                        {
                            Id = "d88755e5-183c-415f-a5fd-d80bf73903aa",
                            Nombre = "Donald Anabel Toledo"
                        },
                        new
                        {
                            Id = "da863279-512f-4519-bc31-0631784bbbe8",
                            Nombre = "Felipa Rick Maduro"
                        },
                        new
                        {
                            Id = "dbc2bdda-f560-4c6e-a174-194e1156e1b0",
                            Nombre = "Nicolás Rick Toledo"
                        },
                        new
                        {
                            Id = "dc43254f-d719-4bed-9cca-38e2e6ef4202",
                            Nombre = "Nicolás Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "df08a3ae-1a9a-469d-8ffd-a7e9130127b4",
                            Nombre = "Alba Silvana Toledo"
                        },
                        new
                        {
                            Id = "e04c101d-158a-4d18-9b14-f2be998f89ec",
                            Nombre = "Donald Murty Uribe"
                        },
                        new
                        {
                            Id = "e0c907b4-5439-4f72-8856-c41c9cd4d416",
                            Nombre = "Farid Freddy Herrera"
                        },
                        new
                        {
                            Id = "e0eeeb02-f794-40a5-994c-92afa06d34f6",
                            Nombre = "Donald Teodoro Trump"
                        },
                        new
                        {
                            Id = "e2d6c002-18ee-44eb-a880-645d19c6b632",
                            Nombre = "Eusebio Silvana Toledo"
                        },
                        new
                        {
                            Id = "e38825c9-5938-4147-9eec-b55c91558cd1",
                            Nombre = "Eusebio Rick Maduro"
                        },
                        new
                        {
                            Id = "e3da6055-667b-4695-9d69-771a8c4247c8",
                            Nombre = "Farid Freddy Trump"
                        },
                        new
                        {
                            Id = "e43999a1-5ec4-4e62-8152-8711a2b42600",
                            Nombre = "Felipa Teodoro Herrera"
                        },
                        new
                        {
                            Id = "e642effe-7e58-402f-bed4-8fbd8f4d2a33",
                            Nombre = "Alba Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "e66099fc-5735-4f91-ad40-3fcdb9c1ae78",
                            Nombre = "Nicolás Rick Sarmiento"
                        },
                        new
                        {
                            Id = "e88e4c1b-6137-4a6a-b4dd-a0c546176796",
                            Nombre = "Felipa Silvana Uribe"
                        },
                        new
                        {
                            Id = "e8be7230-899a-475b-a5c8-e5c075d836f6",
                            Nombre = "Alvaro Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "e8d4a20b-f3ea-4174-940a-bcada0fb7d64",
                            Nombre = "Nicolás Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "e8d54bc7-f306-4961-9ad0-fcf090c6b077",
                            Nombre = "Alvaro Teodoro Herrera"
                        },
                        new
                        {
                            Id = "e971100e-bbf6-4f5f-8800-2e02965ac753",
                            Nombre = "Farid Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "e9955902-edaf-475b-b206-dfd03091419e",
                            Nombre = "Eusebio Teodoro Toledo"
                        },
                        new
                        {
                            Id = "ea9dd874-abca-4311-97cf-ae3cbcb324eb",
                            Nombre = "Donald Freddy Toledo"
                        },
                        new
                        {
                            Id = "eb22fad9-341d-4aa7-b856-45dfd0721d35",
                            Nombre = "Alvaro Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "eb965849-778d-4b88-98c6-68d3eabda950",
                            Nombre = "Eusebio Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "ec73edca-97a7-4f33-a4ed-5c39e7b67481",
                            Nombre = "Eusebio Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "ee67f156-1bcd-40a4-8514-75e9e09ea7e1",
                            Nombre = "Alba Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "efd72e3d-32f9-40c1-b0d3-aa2d237a172a",
                            Nombre = "Alba Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "efe486df-b7c4-48d0-90d2-9177221e802e",
                            Nombre = "Felipa Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "f0b14e53-3948-4453-8506-7c8590593de4",
                            Nombre = "Eusebio Murty Trump"
                        },
                        new
                        {
                            Id = "f1e88cf6-787b-4794-a7be-4ed5363f6f4a",
                            Nombre = "Alvaro Freddy Maduro"
                        },
                        new
                        {
                            Id = "f209a4c4-753f-420f-8efb-8a6f3f73f962",
                            Nombre = "Felipa Teodoro Maduro"
                        },
                        new
                        {
                            Id = "f26fad02-0da0-414b-bc89-107db4927e19",
                            Nombre = "Farid Diomedes Herrera"
                        },
                        new
                        {
                            Id = "f3619a48-e848-461d-8749-fc3d6795dead",
                            Nombre = "Donald Murty Ruiz"
                        },
                        new
                        {
                            Id = "f4003e1c-2f7f-484c-90ff-42993010a33c",
                            Nombre = "Donald Diomedes Toledo"
                        },
                        new
                        {
                            Id = "f51ccecb-d225-4ff7-b122-6248a8804c38",
                            Nombre = "Alvaro Anabel Toledo"
                        },
                        new
                        {
                            Id = "f53344ea-05b9-41c5-bd5c-42ec2375ad63",
                            Nombre = "Alvaro Anabel Trump"
                        },
                        new
                        {
                            Id = "f5695459-ce39-4e6a-baaa-d1b2470bf023",
                            Nombre = "Nicolás Freddy Uribe"
                        },
                        new
                        {
                            Id = "f6c9025f-e206-429a-8cb6-35a90813e5c9",
                            Nombre = "Farid Murty Toledo"
                        },
                        new
                        {
                            Id = "f8168d56-c5f5-473d-9905-00aa53c53d4c",
                            Nombre = "Nicolás Silvana Uribe"
                        },
                        new
                        {
                            Id = "f8893c43-0086-415d-94eb-7ebd3335a018",
                            Nombre = "Donald Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "fa11c1e5-2984-48b4-ad1b-0cd76c5feea6",
                            Nombre = "Eusebio Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "fb29e2c4-d305-48e9-8c3b-3dc07eacceaa",
                            Nombre = "Farid Murty Ruiz"
                        },
                        new
                        {
                            Id = "fb8f3c7a-6de8-4082-9b11-927f64c3f314",
                            Nombre = "Eusebio Teodoro Herrera"
                        },
                        new
                        {
                            Id = "fb947eca-3049-4519-b1ee-c492932b7515",
                            Nombre = "Farid Anabel Toledo"
                        },
                        new
                        {
                            Id = "fbdef0d7-6247-4784-8adc-c9093bf36d52",
                            Nombre = "Farid Silvana Herrera"
                        },
                        new
                        {
                            Id = "fcca12af-62b7-4d61-9592-f71073650186",
                            Nombre = "Felipa Nicomedes Trump"
                        },
                        new
                        {
                            Id = "fd002eda-8fa0-42e2-9c06-1faee9fda365",
                            Nombre = "Felipa Teodoro Toledo"
                        },
                        new
                        {
                            Id = "fd680982-9fd9-4665-b86c-d85e69d3fd9a",
                            Nombre = "Farid Anabel Uribe"
                        },
                        new
                        {
                            Id = "fdaebeac-5de5-4aee-bfeb-b683d7bc7f9e",
                            Nombre = "Eusebio Anabel Trump"
                        },
                        new
                        {
                            Id = "fe4e6f0d-6a6f-417a-9cde-91c47ec37b46",
                            Nombre = "Alba Murty Trump"
                        },
                        new
                        {
                            Id = "ff8e3b64-1c6b-4ca8-85a9-2f5fce8268a7",
                            Nombre = "Felipa Murty Sarmiento"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = "61221d7f-01ed-4713-a673-9ab59e058f4d",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "1f33e0c5-3bc8-4629-a406-bf89598515f9",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "53e84b02-cce4-4abf-b01a-ce9321ad9949",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "550c8665-bcdf-456b-9618-5fb81c492e13",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "31feca3b-d741-4352-982b-d4d50f5940fd",
                            Nombre = "Programacion"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dirección")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscuelaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AñoDeCreación")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEscuela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = "e3f134cf-21d0-40ca-bcb2-7fde285717aa",
                            AñoDeCreación = 2005,
                            Ciudad = " Bogota",
                            Dirección = " Avda siempre viva",
                            Nombre = " Platzi School",
                            Pais = " Colombia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AsignaturaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Escuela", null)
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platzi_ASP_NET_CORE.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
