// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platzi_ASP_NET_CORE.Models;

#nullable disable

namespace Platzi_ASP_NET_CORE.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20220524231106_manytomany")]
    partial class manytomany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = "00ac316e-5983-42c7-86db-496eb5b15f3f",
                            Nombre = "Felipa Diomedes Maduro"
                        },
                        new
                        {
                            Id = "0339e116-df70-4281-95d3-15dca3ec5d0b",
                            Nombre = "Nicolás Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "03eb1c6f-0cb7-4c28-88a4-ff27010e3147",
                            Nombre = "Eusebio Diomedes Toledo"
                        },
                        new
                        {
                            Id = "05034d17-56fc-453b-8b2c-07e795373763",
                            Nombre = "Alvaro Silvana Toledo"
                        },
                        new
                        {
                            Id = "05ed7fff-bde5-4ce5-97d0-b6d45ff2e7a0",
                            Nombre = "Felipa Rick Trump"
                        },
                        new
                        {
                            Id = "0642d2b7-0c41-40d6-aba5-54ff50eba06b",
                            Nombre = "Alba Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "0675035b-853b-45f6-a89e-5050435daeae",
                            Nombre = "Eusebio Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "07af408b-75cb-4adb-8b8d-d5a83d67c308",
                            Nombre = "Eusebio Teodoro Toledo"
                        },
                        new
                        {
                            Id = "0a46fbff-d46b-4031-ba5b-34c7b554a267",
                            Nombre = "Nicolás Freddy Uribe"
                        },
                        new
                        {
                            Id = "0c4703cd-6021-4f72-a6ed-e1d49b1aa611",
                            Nombre = "Eusebio Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "0c55cfa8-a58b-4e4e-8303-6c23362d9c2a",
                            Nombre = "Eusebio Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "0cb72dae-e61f-425a-8767-c9e23503601f",
                            Nombre = "Eusebio Rick Herrera"
                        },
                        new
                        {
                            Id = "0d43443c-ac35-40d7-a33a-6ee80d066dbb",
                            Nombre = "Nicolás Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "0dec3556-4e2f-48e0-b946-129e80205daf",
                            Nombre = "Nicolás Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "0e093f44-3878-40ae-89e8-90c1ab11edec",
                            Nombre = "Nicolás Freddy Toledo"
                        },
                        new
                        {
                            Id = "0efb53c3-dd9a-47e2-8945-0681931c369a",
                            Nombre = "Nicolás Freddy Ruiz"
                        },
                        new
                        {
                            Id = "0f6c937e-3814-4d27-87b0-68946a55c650",
                            Nombre = "Alba Freddy Trump"
                        },
                        new
                        {
                            Id = "101eaafe-36cc-479d-b09a-d8ea4ab18c81",
                            Nombre = "Nicolás Murty Herrera"
                        },
                        new
                        {
                            Id = "11a02e41-09e9-44b7-aee7-1a7e32249b6f",
                            Nombre = "Eusebio Anabel Maduro"
                        },
                        new
                        {
                            Id = "11b3166f-09e7-47e3-837e-f4ee9309d864",
                            Nombre = "Farid Anabel Maduro"
                        },
                        new
                        {
                            Id = "12ff6df9-a149-4d04-8a1b-65d2f3b8bd60",
                            Nombre = "Eusebio Murty Sarmiento"
                        },
                        new
                        {
                            Id = "13387c22-859c-4bb7-aac1-3fab1968c366",
                            Nombre = "Eusebio Silvana Trump"
                        },
                        new
                        {
                            Id = "1442caa1-eb6b-4194-8cf1-a1cdb7b0e587",
                            Nombre = "Alvaro Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "1549d216-77fb-406f-ac48-0e2fd66c2987",
                            Nombre = "Felipa Diomedes Trump"
                        },
                        new
                        {
                            Id = "15d2d306-8926-4539-9936-127344ad2643",
                            Nombre = "Alba Teodoro Maduro"
                        },
                        new
                        {
                            Id = "171d7ad8-886e-40a8-b19c-f2ae548608ce",
                            Nombre = "Donald Teodoro Herrera"
                        },
                        new
                        {
                            Id = "176713d1-ff48-4379-8f97-6fc4b04b1193",
                            Nombre = "Alba Silvana Trump"
                        },
                        new
                        {
                            Id = "190d8e21-1b7d-4ce5-8066-ec79d3e19cb4",
                            Nombre = "Felipa Rick Uribe"
                        },
                        new
                        {
                            Id = "1b0a2d20-9e35-4345-8063-ffdc70c8e2c6",
                            Nombre = "Alvaro Anabel Uribe"
                        },
                        new
                        {
                            Id = "1b0ccfc3-c6b8-4496-9dbc-dc8bd6ffffc6",
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "1b5fe09c-019e-4bce-aaed-9d1da6f871b8",
                            Nombre = "Farid Rick Sarmiento"
                        },
                        new
                        {
                            Id = "1b684a3e-c9f9-482d-a163-832d4a2bdeb8",
                            Nombre = "Donald Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "1bbd24ed-05cc-4c16-89f4-ec8abecace0c",
                            Nombre = "Donald Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "1ca4ba13-a3b9-4025-a559-1df1f7c406c6",
                            Nombre = "Alba Freddy Ruiz"
                        },
                        new
                        {
                            Id = "1db6fc4a-bfcc-4859-9324-e5fae39a55fc",
                            Nombre = "Nicolás Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "1dde4d20-4171-4d81-b2ea-9a568bb9e349",
                            Nombre = "Donald Silvana Toledo"
                        },
                        new
                        {
                            Id = "1e05f652-526c-4d89-a639-cc2db8a8d884",
                            Nombre = "Alvaro Teodoro Maduro"
                        },
                        new
                        {
                            Id = "1eb486f9-8e5e-4ebe-a9ee-b8f002a92e45",
                            Nombre = "Eusebio Murty Trump"
                        },
                        new
                        {
                            Id = "1efed7ce-a5bc-461e-83a1-ac9970ccb6c3",
                            Nombre = "Farid Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "1fb9bc48-bfab-4af4-afed-680ae7202bfe",
                            Nombre = "Alba Teodoro Uribe"
                        },
                        new
                        {
                            Id = "1ff3e15c-7447-436e-b4ce-1b8b28254390",
                            Nombre = "Alvaro Freddy Herrera"
                        },
                        new
                        {
                            Id = "2059dfa8-471f-416f-9a70-bc6baa976cca",
                            Nombre = "Alba Murty Toledo"
                        },
                        new
                        {
                            Id = "20c2ccdd-3f65-47e1-82df-a2902a7f6ce6",
                            Nombre = "Eusebio Freddy Toledo"
                        },
                        new
                        {
                            Id = "21d7dbf5-97fa-4e2f-8c75-2b1d1d09d6c5",
                            Nombre = "Donald Rick Maduro"
                        },
                        new
                        {
                            Id = "22b9da7d-a12c-44e8-a70a-b5eab51a6a04",
                            Nombre = "Eusebio Rick Ruiz"
                        },
                        new
                        {
                            Id = "22caf71c-0fc9-4f39-aefb-d2dc6c3aadc7",
                            Nombre = "Donald Anabel Ruiz"
                        },
                        new
                        {
                            Id = "22e57fae-4b93-4d55-9e0a-3eb3c8c9036a",
                            Nombre = "Alba Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "232ace42-3cf4-4157-9056-cc97531769f2",
                            Nombre = "Alvaro Anabel Herrera"
                        },
                        new
                        {
                            Id = "23887063-d97f-4ffc-a1ee-5fd351b1ddf6",
                            Nombre = "Felipa Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "23deb78f-6472-4166-994b-a0b25cbeed88",
                            Nombre = "Alvaro Teodoro Trump"
                        },
                        new
                        {
                            Id = "24e04a7c-5821-44bd-a641-ea490fe82a69",
                            Nombre = "Farid Diomedes Toledo"
                        },
                        new
                        {
                            Id = "26049acb-2cb0-4062-b769-ab161740cbbc",
                            Nombre = "Farid Freddy Uribe"
                        },
                        new
                        {
                            Id = "2626dfd9-6192-440b-a177-3f5fea7c7c0e",
                            Nombre = "Nicolás Rick Trump"
                        },
                        new
                        {
                            Id = "26d04275-8568-4067-adb0-fb72976cb2cd",
                            Nombre = "Felipa Freddy Maduro"
                        },
                        new
                        {
                            Id = "26d41fd7-757a-40e0-be59-9fc60f281cb6",
                            Nombre = "Alvaro Murty Herrera"
                        },
                        new
                        {
                            Id = "274df7d8-8278-4a2a-9b7e-0d13213af9f0",
                            Nombre = "Donald Teodoro Toledo"
                        },
                        new
                        {
                            Id = "277090ca-cfea-4fad-80c4-27ea5e3916e4",
                            Nombre = "Felipa Teodoro Herrera"
                        },
                        new
                        {
                            Id = "27b00c31-11f3-4518-92b9-98ee58618745",
                            Nombre = "Donald Rick Ruiz"
                        },
                        new
                        {
                            Id = "2848d4cd-efeb-4bc3-877d-1781ec1dc5c9",
                            Nombre = "Eusebio Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "284d7b53-6fdf-4966-bc61-e9fcd5ec01cf",
                            Nombre = "Alvaro Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "297b213e-ff0a-4a2c-81d8-941821e204f9",
                            Nombre = "Felipa Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "2a0024c3-8a7c-4c64-8f04-dbe979d4ddfb",
                            Nombre = "Eusebio Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "2b39fe83-e8a8-43b5-bacf-75d2e9d96872",
                            Nombre = "Nicolás Anabel Toledo"
                        },
                        new
                        {
                            Id = "2c19ff35-c47c-4075-8513-f447a46ae371",
                            Nombre = "Nicolás Teodoro Herrera"
                        },
                        new
                        {
                            Id = "2c2a34a7-4fc7-4f24-b2d4-c72e7849a038",
                            Nombre = "Eusebio Freddy Uribe"
                        },
                        new
                        {
                            Id = "2c96d22d-99a9-4260-8c48-90b4727a63ab",
                            Nombre = "Alvaro Rick Uribe"
                        },
                        new
                        {
                            Id = "2c9b48d1-4a0a-4b5d-8442-7310f815fa25",
                            Nombre = "Eusebio Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "2e04eefd-270f-48b6-98ab-94bd31dfe485",
                            Nombre = "Eusebio Freddy Trump"
                        },
                        new
                        {
                            Id = "2e155112-a609-481a-a9db-c60e1c53f7ca",
                            Nombre = "Donald Nicomedes Trump"
                        },
                        new
                        {
                            Id = "2e80eecd-4c98-48e0-b1f4-daa1b299b354",
                            Nombre = "Alvaro Anabel Ruiz"
                        },
                        new
                        {
                            Id = "2e946b25-683e-4613-a135-085211a50298",
                            Nombre = "Eusebio Diomedes Trump"
                        },
                        new
                        {
                            Id = "2eb76c2c-fa9e-4317-9d5c-9a0c3009bd0a",
                            Nombre = "Alvaro Murty Uribe"
                        },
                        new
                        {
                            Id = "2ef2f49c-44e4-4264-847b-5aa691e09781",
                            Nombre = "Donald Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "2fc5d8a0-b225-4e6d-9f1e-a8da90cddb1e",
                            Nombre = "Farid Anabel Uribe"
                        },
                        new
                        {
                            Id = "2fee7990-db3b-4593-b249-c2e01651d38f",
                            Nombre = "Felipa Anabel Herrera"
                        },
                        new
                        {
                            Id = "2feeed7c-1f87-4067-82ea-01abedebe86d",
                            Nombre = "Donald Murty Uribe"
                        },
                        new
                        {
                            Id = "2ff5f352-e534-46ac-82d7-6480dc8b38d8",
                            Nombre = "Alba Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "3084d79a-f12b-4a93-bdda-eee6901c2bd3",
                            Nombre = "Farid Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "30973561-5696-4fc8-b421-af0759c5ef55",
                            Nombre = "Donald Rick Uribe"
                        },
                        new
                        {
                            Id = "30f49f9b-e86d-426a-95f5-0e7ff4ddfc5a",
                            Nombre = "Alvaro Rick Maduro"
                        },
                        new
                        {
                            Id = "34591970-1e73-43df-aee5-efcb983be721",
                            Nombre = "Alba Rick Toledo"
                        },
                        new
                        {
                            Id = "34fccaf5-357e-4b14-a2ad-4a68ec81bb67",
                            Nombre = "Felipa Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "35e815e4-e784-4672-b7ec-442c698f3228",
                            Nombre = "Farid Freddy Maduro"
                        },
                        new
                        {
                            Id = "377acfb9-4764-43de-8f79-5f78c456c4ef",
                            Nombre = "Donald Murty Sarmiento"
                        },
                        new
                        {
                            Id = "37a8504a-78af-4811-86fd-0b59570664e5",
                            Nombre = "Eusebio Rick Uribe"
                        },
                        new
                        {
                            Id = "37f4136e-0b18-4182-aa11-a4735ad68763",
                            Nombre = "Donald Silvana Maduro"
                        },
                        new
                        {
                            Id = "392a5fc4-5860-4551-8153-08ca95912d4d",
                            Nombre = "Alba Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "39a5263a-eda7-45b5-995e-2a3f0dbe23b8",
                            Nombre = "Donald Teodoro Uribe"
                        },
                        new
                        {
                            Id = "39d8def5-aca0-4dfd-a2f3-a9b74d348947",
                            Nombre = "Nicolás Anabel Ruiz"
                        },
                        new
                        {
                            Id = "3abbe9b2-2d9d-4e3d-9b4d-ceb00b8418f4",
                            Nombre = "Donald Teodoro Maduro"
                        },
                        new
                        {
                            Id = "3b4e1f81-31ee-40b9-82ec-ee8fb349d348",
                            Nombre = "Alba Nicomedes Trump"
                        },
                        new
                        {
                            Id = "3c222f28-5352-43aa-8df8-9cb28f1301ad",
                            Nombre = "Alvaro Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "3d15ecc4-9f7c-433f-938b-d7fc05bbc9a8",
                            Nombre = "Felipa Murty Herrera"
                        },
                        new
                        {
                            Id = "3d1daff6-04c3-4fb5-a0cb-33459881729f",
                            Nombre = "Eusebio Diomedes Uribe"
                        },
                        new
                        {
                            Id = "3dbfb0e5-c95a-4b5e-943e-119c282655d1",
                            Nombre = "Nicolás Teodoro Toledo"
                        },
                        new
                        {
                            Id = "3defb63b-db17-4e50-9067-727e241919d3",
                            Nombre = "Farid Rick Maduro"
                        },
                        new
                        {
                            Id = "3e51b040-f575-4066-bcf4-2c64516dbb76",
                            Nombre = "Farid Teodoro Trump"
                        },
                        new
                        {
                            Id = "3fd92f50-39cb-4428-a9a5-d2e20ebe3876",
                            Nombre = "Nicolás Silvana Uribe"
                        },
                        new
                        {
                            Id = "3fdeff7f-5cfb-43ca-96dd-13feee7f6bbe",
                            Nombre = "Farid Diomedes Uribe"
                        },
                        new
                        {
                            Id = "40619fdb-468a-4f94-99ac-23e279b466d7",
                            Nombre = "Farid Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "40e51636-5807-4737-a6c0-41cb7f88e957",
                            Nombre = "Farid Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "41904db1-6789-47ca-9e8d-2b1b1ee42bf5",
                            Nombre = "Donald Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "425f990b-37c3-43fd-a160-da4ba15e1ccd",
                            Nombre = "Farid Freddy Trump"
                        },
                        new
                        {
                            Id = "427255cc-a44f-4475-b2d4-4f5e729fe46b",
                            Nombre = "Alba Diomedes Uribe"
                        },
                        new
                        {
                            Id = "428c29ad-8c27-446a-9730-4bf581d0c951",
                            Nombre = "Alvaro Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "44267c5e-973e-4db1-aa3b-a41cd9e8ddc7",
                            Nombre = "Donald Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "44486a4d-f1d9-4518-b25e-b749329cbc2b",
                            Nombre = "Nicolás Anabel Maduro"
                        },
                        new
                        {
                            Id = "4495bd1f-f580-4e23-8bb4-ad854b76b1f3",
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            Id = "44c4c8c2-bc9a-4073-ba37-5076b2267665",
                            Nombre = "Felipa Anabel Maduro"
                        },
                        new
                        {
                            Id = "44da45d9-81f5-4097-9d45-22d87db4ba62",
                            Nombre = "Eusebio Rick Trump"
                        },
                        new
                        {
                            Id = "45b4373b-bd9e-41b3-9722-da61275b59b2",
                            Nombre = "Donald Silvana Uribe"
                        },
                        new
                        {
                            Id = "45b44a7c-664f-419a-b205-d3df51bb918c",
                            Nombre = "Felipa Freddy Uribe"
                        },
                        new
                        {
                            Id = "45b81501-4f58-4573-a329-ac717cb74500",
                            Nombre = "Alvaro Freddy Trump"
                        },
                        new
                        {
                            Id = "466648c2-2583-49a3-aeac-d9d74bf0a483",
                            Nombre = "Nicolás Silvana Ruiz"
                        },
                        new
                        {
                            Id = "46869740-ae0e-4c9a-bc6f-5534d4642c05",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "46affa0e-c03a-4ded-9d79-8fe54f9aef7e",
                            Nombre = "Alba Murty Herrera"
                        },
                        new
                        {
                            Id = "46d0c81d-c9f6-4226-9480-e62af8fc9678",
                            Nombre = "Farid Murty Toledo"
                        },
                        new
                        {
                            Id = "472ac53e-54a1-4d87-8f2c-8394c29f9467",
                            Nombre = "Felipa Freddy Toledo"
                        },
                        new
                        {
                            Id = "4819edb1-e499-4a9e-8c01-17c4e7beca29",
                            Nombre = "Alba Murty Sarmiento"
                        },
                        new
                        {
                            Id = "4842ef26-eae9-483f-800c-b3d4f23b50c4",
                            Nombre = "Farid Diomedes Trump"
                        },
                        new
                        {
                            Id = "4a48764c-932d-4b32-9e99-82b4eeaf526e",
                            Nombre = "Donald Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "4afe4c73-9a6a-43b1-8073-0b37d780f032",
                            Nombre = "Donald Anabel Herrera"
                        },
                        new
                        {
                            Id = "4bb0680b-bcba-41db-8945-32fd597f1e99",
                            Nombre = "Felipa Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "4ca14669-96b5-4cb4-b3e5-0bdf0498f44b",
                            Nombre = "Donald Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "4e5e39a7-7c03-4d98-b3c3-5a59216f81b8",
                            Nombre = "Donald Murty Ruiz"
                        },
                        new
                        {
                            Id = "4e8293eb-09fe-4cc5-aadb-c76d3cbddb90",
                            Nombre = "Nicolás Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "4e9c52a8-c1ce-4a5a-bc33-b96f968e7e8e",
                            Nombre = "Farid Teodoro Maduro"
                        },
                        new
                        {
                            Id = "4f1ec282-25aa-4c25-9131-8f6a531c6c3d",
                            Nombre = "Eusebio Rick Sarmiento"
                        },
                        new
                        {
                            Id = "4f49a9d4-7010-4e7a-9a68-1330546c937b",
                            Nombre = "Alvaro Murty Trump"
                        },
                        new
                        {
                            Id = "5071a42c-1bc2-4e2f-baa8-7c7cdc7e3e90",
                            Nombre = "Felipa Freddy Ruiz"
                        },
                        new
                        {
                            Id = "50af1461-0ced-4037-a77b-f12b34e3c349",
                            Nombre = "Felipa Rick Ruiz"
                        },
                        new
                        {
                            Id = "511fa7ea-ca00-43f9-8277-274d773178c5",
                            Nombre = "Farid Anabel Toledo"
                        },
                        new
                        {
                            Id = "51b7f905-177a-4611-a11a-f1c91b2bde53",
                            Nombre = "Alba Silvana Herrera"
                        },
                        new
                        {
                            Id = "51c810ee-0c28-44a7-9f50-56ec501a88da",
                            Nombre = "Nicolás Anabel Trump"
                        },
                        new
                        {
                            Id = "532fa71d-16bd-42a7-89b8-40ae41075abf",
                            Nombre = "Felipa Teodoro Uribe"
                        },
                        new
                        {
                            Id = "53d666f4-f8ab-40cd-92c9-93ddd017d4b8",
                            Nombre = "Alvaro Teodoro Toledo"
                        },
                        new
                        {
                            Id = "53e12d11-3168-41c6-baa4-c3928e799993",
                            Nombre = "Alba Anabel Trump"
                        },
                        new
                        {
                            Id = "53f852c3-3fc7-4dbe-b957-f7032ef000c5",
                            Nombre = "Donald Silvana Herrera"
                        },
                        new
                        {
                            Id = "5487634c-ad5c-4a7f-adee-5d5a1e1c36f1",
                            Nombre = "Alba Rick Maduro"
                        },
                        new
                        {
                            Id = "54b19032-1121-4cb5-8185-9d2635554f73",
                            Nombre = "Eusebio Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "550645bb-ebff-4755-8d3b-4d15a8fe2dc4",
                            Nombre = "Alvaro Diomedes Uribe"
                        },
                        new
                        {
                            Id = "55f420b3-5523-4e3d-a14a-437519a5e0c6",
                            Nombre = "Farid Freddy Toledo"
                        },
                        new
                        {
                            Id = "561caf32-f1e0-4806-b605-4dbf4c4e4341",
                            Nombre = "Alvaro Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "56735d8e-2392-4c05-8434-d1e40f151a34",
                            Nombre = "Felipa Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "5695a2ac-186e-4dd6-a416-06d15876f88a",
                            Nombre = "Felipa Silvana Trump"
                        },
                        new
                        {
                            Id = "57d85ec1-a95c-4d1f-9e09-90748b816c50",
                            Nombre = "Alvaro Murty Ruiz"
                        },
                        new
                        {
                            Id = "596efbed-5264-488f-b2c0-0c63f2227625",
                            Nombre = "Felipa Anabel Trump"
                        },
                        new
                        {
                            Id = "59b90111-c91b-43b7-88f5-f3a268609065",
                            Nombre = "Alba Teodoro Herrera"
                        },
                        new
                        {
                            Id = "5b103284-a180-4e63-855d-7137dcd8135e",
                            Nombre = "Felipa Rick Maduro"
                        },
                        new
                        {
                            Id = "5b23e359-ac0f-4dcf-ab00-3fae062f80f6",
                            Nombre = "Felipa Rick Sarmiento"
                        },
                        new
                        {
                            Id = "5b354db3-541b-4b09-9811-55c1507a8bf0",
                            Nombre = "Nicolás Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "5c0d6e78-698f-45ed-9cb2-28626d1b859b",
                            Nombre = "Nicolás Murty Toledo"
                        },
                        new
                        {
                            Id = "5c19e02a-ed7c-41ad-8a90-0322b4050ce7",
                            Nombre = "Eusebio Anabel Ruiz"
                        },
                        new
                        {
                            Id = "5d3df997-ac2e-488c-8cc2-866c1eea5fb4",
                            Nombre = "Felipa Murty Maduro"
                        },
                        new
                        {
                            Id = "5d42fd3c-470e-4a82-a900-d26779b4b3cb",
                            Nombre = "Nicolás Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "5ff4d4c0-1b21-48f1-95c7-9dacf52a0eb1",
                            Nombre = "Eusebio Nicomedes Trump"
                        },
                        new
                        {
                            Id = "60acc6b6-c871-4c6a-87be-7dfb7b49f369",
                            Nombre = "Nicolás Anabel Herrera"
                        },
                        new
                        {
                            Id = "60e4b04e-8243-4320-aace-074af0b2b610",
                            Nombre = "Alba Freddy Uribe"
                        },
                        new
                        {
                            Id = "61068050-651c-47ad-a408-65b21851b635",
                            Nombre = "Farid Murty Ruiz"
                        },
                        new
                        {
                            Id = "611bb8bb-8294-4639-8f49-2b0a61b47dbf",
                            Nombre = "Alvaro Murty Maduro"
                        },
                        new
                        {
                            Id = "613ae267-942b-4155-bfc7-c4172bcb842b",
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            Id = "62257985-a8e0-4919-8bc5-7dfe5c667e0d",
                            Nombre = "Alvaro Rick Trump"
                        },
                        new
                        {
                            Id = "62b5cfb0-df8f-4c60-b5f4-7d8b4187e714",
                            Nombre = "Nicolás Diomedes Uribe"
                        },
                        new
                        {
                            Id = "63aff01f-9c29-447e-9915-6eb323772f64",
                            Nombre = "Alba Freddy Maduro"
                        },
                        new
                        {
                            Id = "63e405c6-8e74-4062-bcc4-daadc54507b0",
                            Nombre = "Nicolás Nicomedes Trump"
                        },
                        new
                        {
                            Id = "66caba72-a555-437a-91cd-f03882d6a15b",
                            Nombre = "Nicolás Murty Trump"
                        },
                        new
                        {
                            Id = "6746fb64-89cf-46e6-8a10-7340eebd993d",
                            Nombre = "Nicolás Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "67fa0d68-df8d-41ff-8bb4-5f2be964aacb",
                            Nombre = "Alvaro Rick Ruiz"
                        },
                        new
                        {
                            Id = "684726f5-8f69-41a3-8512-c00652720d42",
                            Nombre = "Nicolás Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "69064b88-5e2b-4c9c-a101-6aaf527ab97f",
                            Nombre = "Donald Diomedes Uribe"
                        },
                        new
                        {
                            Id = "6962b718-868e-42b7-b546-ab92d903973e",
                            Nombre = "Nicolás Teodoro Trump"
                        },
                        new
                        {
                            Id = "6ba6f4f8-eb4b-409f-8f35-020cf813b0b0",
                            Nombre = "Donald Murty Trump"
                        },
                        new
                        {
                            Id = "6cbe04f2-1c56-427e-aa86-f86a6f4ad875",
                            Nombre = "Felipa Anabel Uribe"
                        },
                        new
                        {
                            Id = "6cd04163-239e-4446-851a-5f816d39e88c",
                            Nombre = "Felipa Murty Uribe"
                        },
                        new
                        {
                            Id = "6d8bd397-fd8c-476e-bd20-39cbd5b3a3d5",
                            Nombre = "Alvaro Nicomedes Trump"
                        },
                        new
                        {
                            Id = "6de5f1e2-511c-4c04-948c-dcdf63a915c1",
                            Nombre = "Felipa Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "6e3a1dd1-92ed-4af3-92b4-709826e0de69",
                            Nombre = "Alvaro Silvana Trump"
                        },
                        new
                        {
                            Id = "6e768d1c-b79b-4718-8e12-4847dffdc29b",
                            Nombre = "Nicolás Freddy Trump"
                        },
                        new
                        {
                            Id = "6f38c3cb-8830-4589-9483-f978c3d12b23",
                            Nombre = "Nicolás Teodoro Maduro"
                        },
                        new
                        {
                            Id = "6fd7a8b7-ef10-4a2c-91b6-c70df7b9ca88",
                            Nombre = "Farid Silvana Maduro"
                        },
                        new
                        {
                            Id = "708c4f33-1283-40bf-82d0-b41479e4dba5",
                            Nombre = "Nicolás Murty Maduro"
                        },
                        new
                        {
                            Id = "70b4d46d-9cf3-4bd5-9a74-f2d4f3dce15a",
                            Nombre = "Eusebio Silvana Uribe"
                        },
                        new
                        {
                            Id = "7269adb5-f43c-492b-a0c3-518c1cdbb3a2",
                            Nombre = "Donald Freddy Herrera"
                        },
                        new
                        {
                            Id = "7344896e-8832-4280-9ad5-7c33cfde8db3",
                            Nombre = "Donald Diomedes Trump"
                        },
                        new
                        {
                            Id = "73d57a5d-0411-4ad0-805e-82685551dece",
                            Nombre = "Alba Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "740d4139-1077-4b1a-a3ee-092c7893fa9a",
                            Nombre = "Eusebio Freddy Maduro"
                        },
                        new
                        {
                            Id = "74fe93c0-20ff-4575-9720-ebddacbe0522",
                            Nombre = "Alba Diomedes Trump"
                        },
                        new
                        {
                            Id = "75021036-2f11-4164-be9a-682a9e1c00d3",
                            Nombre = "Donald Diomedes Maduro"
                        },
                        new
                        {
                            Id = "75c20aa0-9895-4df1-b938-150670c431a1",
                            Nombre = "Alba Diomedes Herrera"
                        },
                        new
                        {
                            Id = "7612d5f4-384a-4a4f-982e-04184056a1e5",
                            Nombre = "Donald Murty Toledo"
                        },
                        new
                        {
                            Id = "765aa231-f418-438c-9a9f-22cb14ce4d29",
                            Nombre = "Alvaro Freddy Ruiz"
                        },
                        new
                        {
                            Id = "77cc01a6-8059-490b-b19c-f8937af3fe53",
                            Nombre = "Farid Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "77ec4a10-ec7e-48b7-9196-863ff96ef038",
                            Nombre = "Nicolás Silvana Trump"
                        },
                        new
                        {
                            Id = "78c98cb8-3a46-4a8b-98f0-4a5b4c6c5434",
                            Nombre = "Donald Silvana Trump"
                        },
                        new
                        {
                            Id = "7907165b-0dc6-40ad-83fc-7f56d821106a",
                            Nombre = "Farid Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "79137230-00f6-4d7f-ae61-9ebf02fe9891",
                            Nombre = "Farid Silvana Toledo"
                        },
                        new
                        {
                            Id = "7ac7b58f-b604-4e45-a8fb-c8a451632068",
                            Nombre = "Alba Rick Uribe"
                        },
                        new
                        {
                            Id = "7ad3af48-d11d-458a-870b-55224b028fe3",
                            Nombre = "Farid Anabel Herrera"
                        },
                        new
                        {
                            Id = "7ba0fe98-1a58-4377-932c-fd3af601891e",
                            Nombre = "Donald Diomedes Herrera"
                        },
                        new
                        {
                            Id = "7bfc0d0e-f5e5-4310-88bf-2b7f5701290f",
                            Nombre = "Alvaro Murty Sarmiento"
                        },
                        new
                        {
                            Id = "7c528aa6-b95d-4ddb-9a08-13ecb49accf0",
                            Nombre = "Eusebio Murty Ruiz"
                        },
                        new
                        {
                            Id = "7cf7a54c-deba-4fc7-a33a-bc996cd8ca7e",
                            Nombre = "Farid Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "7cf98a1f-933c-456c-8f24-fc191b33b000",
                            Nombre = "Felipa Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "7d59d3ce-fa28-40d8-bfa0-58e5f08fab72",
                            Nombre = "Eusebio Freddy Ruiz"
                        },
                        new
                        {
                            Id = "7e4b3084-6240-4b96-afa6-aa8ca87101a4",
                            Nombre = "Alvaro Teodoro Herrera"
                        },
                        new
                        {
                            Id = "7edbcfe2-3261-4547-b5c5-623ed5e30425",
                            Nombre = "Eusebio Teodoro Maduro"
                        },
                        new
                        {
                            Id = "7f93da58-d3a1-48bf-9c34-fec165653a93",
                            Nombre = "Nicolás Anabel Uribe"
                        },
                        new
                        {
                            Id = "7fd48754-a51e-462f-9252-aaeabf317a2b",
                            Nombre = "Donald Freddy Maduro"
                        },
                        new
                        {
                            Id = "80d34de6-d1fc-4c7c-ad8a-ffb3a0714fae",
                            Nombre = "Felipa Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "81ac2e0e-4235-4304-83b8-a4557d337150",
                            Nombre = "Felipa Silvana Uribe"
                        },
                        new
                        {
                            Id = "82568419-3d4e-4cb2-9e2e-12c699550afb",
                            Nombre = "Donald Freddy Toledo"
                        },
                        new
                        {
                            Id = "82e45ca5-d6dc-4a55-9197-8da8ee81d38a",
                            Nombre = "Felipa Anabel Toledo"
                        },
                        new
                        {
                            Id = "8320b091-973e-47ce-8fec-6061e1df2bf3",
                            Nombre = "Eusebio Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "83272bfe-c9f8-4dc4-abf2-fb27e134b7e2",
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            Id = "850bbb71-9a40-4a1b-910c-fba9d1cc24b5",
                            Nombre = "Farid Murty Trump"
                        },
                        new
                        {
                            Id = "8511ca98-51e8-4746-9e46-afe7b421d5e4",
                            Nombre = "Alvaro Diomedes Trump"
                        },
                        new
                        {
                            Id = "8552b4b4-0667-4242-9bf6-cb1ab6523894",
                            Nombre = "Eusebio Anabel Trump"
                        },
                        new
                        {
                            Id = "8698f5c8-18fa-4f22-95b8-6877e4bb73e4",
                            Nombre = "Alba Silvana Toledo"
                        },
                        new
                        {
                            Id = "86a3ba8f-e58d-401a-a615-8a5e50a274b8",
                            Nombre = "Felipa Silvana Herrera"
                        },
                        new
                        {
                            Id = "86a63dee-553c-4aed-aacf-2f308c6cad84",
                            Nombre = "Nicolás Freddy Maduro"
                        },
                        new
                        {
                            Id = "875222dc-ce2a-412f-ab66-6540c14eaee5",
                            Nombre = "Alba Rick Sarmiento"
                        },
                        new
                        {
                            Id = "87557748-4364-40b0-b20b-c5a4f37871b0",
                            Nombre = "Felipa Teodoro Toledo"
                        },
                        new
                        {
                            Id = "878da0dc-ef29-45e9-b95f-930dfce13d12",
                            Nombre = "Farid Freddy Ruiz"
                        },
                        new
                        {
                            Id = "884a71fe-52c1-4f5c-aee4-1795a66a455e",
                            Nombre = "Alba Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "888e7486-2c11-4095-a710-a0535b0a5238",
                            Nombre = "Felipa Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "89426f8b-8e01-43c6-bcf9-fa5a7cf81a99",
                            Nombre = "Farid Silvana Uribe"
                        },
                        new
                        {
                            Id = "894f8f9d-67e4-4d3a-84fd-e66ada1f4b44",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "8a96720a-90d2-476c-a341-07eea44b6826",
                            Nombre = "Felipa Anabel Ruiz"
                        },
                        new
                        {
                            Id = "8b09d508-2286-441b-96af-e4a54098e491",
                            Nombre = "Donald Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "8b9278c5-5bb7-489b-ad16-49a03796ac67",
                            Nombre = "Nicolás Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "8c98c786-871c-4235-b8b3-73919c96d4f4",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "8de1af37-f0e2-481e-a7e7-c8be3a95c947",
                            Nombre = "Nicolás Diomedes Herrera"
                        },
                        new
                        {
                            Id = "8f3dadcc-49d9-4d04-af85-fcdb895f7edc",
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            Id = "8f6c0c9a-bd3e-42dd-b594-007816bbf0cb",
                            Nombre = "Alba Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "8ffd0e15-7213-4571-900e-e5442c16f64a",
                            Nombre = "Alba Rick Herrera"
                        },
                        new
                        {
                            Id = "901cfd61-15fa-4f71-b706-39cfdebca64c",
                            Nombre = "Alvaro Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "90fa02a4-eab9-41e7-9ea7-8ceb5eca3c4f",
                            Nombre = "Nicolás Murty Uribe"
                        },
                        new
                        {
                            Id = "91159b69-4523-4210-b608-9a09cd944acb",
                            Nombre = "Alba Anabel Uribe"
                        },
                        new
                        {
                            Id = "914a0b28-e55c-40ae-b745-f1073807f620",
                            Nombre = "Felipa Teodoro Maduro"
                        },
                        new
                        {
                            Id = "91b3f07e-c2b4-4a5b-9b16-807e2aa3f763",
                            Nombre = "Farid Silvana Herrera"
                        },
                        new
                        {
                            Id = "92153735-72b4-4056-ab03-e226a9de83a3",
                            Nombre = "Felipa Teodoro Trump"
                        },
                        new
                        {
                            Id = "92a048f9-ea80-49d6-9321-756de87d9607",
                            Nombre = "Nicolás Murty Ruiz"
                        },
                        new
                        {
                            Id = "9352a968-e2e2-47da-8b18-6828b2eb842b",
                            Nombre = "Farid Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "93faa8eb-7d39-4f4f-b895-c258dc6d8317",
                            Nombre = "Eusebio Anabel Toledo"
                        },
                        new
                        {
                            Id = "94cd0ec6-2df4-48cc-8877-def5f9b7cc4f",
                            Nombre = "Donald Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "96824b6d-c6d5-4262-9816-daf7cd43a5a4",
                            Nombre = "Farid Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "9ab1a2da-ba1f-4cc5-9fa2-22b9d153a43d",
                            Nombre = "Eusebio Silvana Toledo"
                        },
                        new
                        {
                            Id = "9b7a526c-bb92-4efb-a960-1360746dbc9c",
                            Nombre = "Alvaro Anabel Maduro"
                        },
                        new
                        {
                            Id = "9b96ed74-06e5-4717-b960-1f1cdb3cb80f",
                            Nombre = "Felipa Silvana Maduro"
                        },
                        new
                        {
                            Id = "9c41ba49-c7bb-447a-93a5-96d46c9a8c38",
                            Nombre = "Alvaro Silvana Ruiz"
                        },
                        new
                        {
                            Id = "9c889f3f-02f6-4207-ae18-8b76a768b494",
                            Nombre = "Nicolás Murty Sarmiento"
                        },
                        new
                        {
                            Id = "9d8b5716-40ba-4bdf-b95f-5372f0017a51",
                            Nombre = "Farid Rick Trump"
                        },
                        new
                        {
                            Id = "9d931ed3-5756-4580-9c1a-19ff9b78c6fe",
                            Nombre = "Nicolás Diomedes Maduro"
                        },
                        new
                        {
                            Id = "9dc3b087-72f3-4d4a-a4a0-9046bfe88ded",
                            Nombre = "Alba Diomedes Toledo"
                        },
                        new
                        {
                            Id = "9e319647-919b-4ab9-a979-75ceff58c21b",
                            Nombre = "Alba Silvana Uribe"
                        },
                        new
                        {
                            Id = "9e9961e1-f108-4d9a-8ab2-48818ccb0e27",
                            Nombre = "Alvaro Freddy Toledo"
                        },
                        new
                        {
                            Id = "9ebcccb2-c1c3-447a-80c7-142fb0ebd897",
                            Nombre = "Felipa Diomedes Uribe"
                        },
                        new
                        {
                            Id = "a006eba1-2f62-49f8-8c23-1e923a814e81",
                            Nombre = "Eusebio Silvana Herrera"
                        },
                        new
                        {
                            Id = "a0347a00-3870-4ca5-a42a-f147eb228bb0",
                            Nombre = "Farid Silvana Trump"
                        },
                        new
                        {
                            Id = "a0c71711-55a6-4770-8cb1-7a1cc5be5ea4",
                            Nombre = "Felipa Diomedes Herrera"
                        },
                        new
                        {
                            Id = "a19b0f46-4b9e-492f-a0ac-1f99f9d5a2f2",
                            Nombre = "Alba Murty Uribe"
                        },
                        new
                        {
                            Id = "a20b68a7-8bba-4848-af36-e5364708dd15",
                            Nombre = "Alvaro Freddy Uribe"
                        },
                        new
                        {
                            Id = "a23244b6-7e4a-499f-97b3-688dc8b36f32",
                            Nombre = "Alba Silvana Ruiz"
                        },
                        new
                        {
                            Id = "a275745c-bf3d-4699-94dd-759ba4100923",
                            Nombre = "Alvaro Freddy Maduro"
                        },
                        new
                        {
                            Id = "a4d2d11a-de6e-407a-8cf4-f90ffaa9e658",
                            Nombre = "Alvaro Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "a6456a8b-904f-4533-a44a-45cc8900f800",
                            Nombre = "Farid Diomedes Maduro"
                        },
                        new
                        {
                            Id = "a780cc60-998b-4fea-9d39-8ef6cb9e79b6",
                            Nombre = "Eusebio Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "a79eba09-6a70-4d6e-8d64-1650646cfa06",
                            Nombre = "Nicolás Rick Sarmiento"
                        },
                        new
                        {
                            Id = "a7bbedea-515b-48f2-be15-eb7f0d69dfb2",
                            Nombre = "Felipa Freddy Herrera"
                        },
                        new
                        {
                            Id = "a96b3fbe-1a60-4adf-9ecd-ebcd7c7784b1",
                            Nombre = "Nicolás Rick Uribe"
                        },
                        new
                        {
                            Id = "a9d5ebaf-d85f-457e-92e9-ae827561ef29",
                            Nombre = "Farid Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "ab24d18b-3f2d-4a8c-8e18-24ce0ff027fd",
                            Nombre = "Farid Rick Uribe"
                        },
                        new
                        {
                            Id = "ab65300d-5cb1-453f-87e7-1b8f4f30692c",
                            Nombre = "Felipa Murty Toledo"
                        },
                        new
                        {
                            Id = "abb68cba-365d-4a9b-a306-0fbd173187bd",
                            Nombre = "Alvaro Anabel Toledo"
                        },
                        new
                        {
                            Id = "abe56d33-e76c-4af9-8909-79839cca986f",
                            Nombre = "Alvaro Diomedes Herrera"
                        },
                        new
                        {
                            Id = "aca999b4-ec2a-4e02-92a1-610f2cbc3184",
                            Nombre = "Farid Murty Sarmiento"
                        },
                        new
                        {
                            Id = "adce9d9d-8d4c-44fc-9ee9-b4fbb937da1b",
                            Nombre = "Donald Murty Herrera"
                        },
                        new
                        {
                            Id = "ae024cd9-93ef-4b1c-87cc-17002bd37035",
                            Nombre = "Alba Diomedes Maduro"
                        },
                        new
                        {
                            Id = "af001482-f0d9-4274-aeaf-01d61892a90d",
                            Nombre = "Felipa Diomedes Toledo"
                        },
                        new
                        {
                            Id = "af665e75-54fe-4dde-984d-db7ef8f7a403",
                            Nombre = "Eusebio Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "b09e3d34-5a94-4e15-902c-1ee722349acb",
                            Nombre = "Alba Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "b11f52a8-650e-4229-8c1a-86cf7207c39b",
                            Nombre = "Eusebio Teodoro Trump"
                        },
                        new
                        {
                            Id = "b123641b-0852-4d3f-bf32-4cbdb6b344bb",
                            Nombre = "Nicolás Silvana Toledo"
                        },
                        new
                        {
                            Id = "b1c8cbef-3a04-4304-b4eb-e98e2c4f6c2d",
                            Nombre = "Farid Rick Herrera"
                        },
                        new
                        {
                            Id = "b21bd348-ebbd-44c3-8b38-0cdcbcd0574d",
                            Nombre = "Nicolás Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "b354ba3d-71bd-4d33-b0cb-3aca1270e5e6",
                            Nombre = "Felipa Murty Sarmiento"
                        },
                        new
                        {
                            Id = "b39b485d-fde2-488c-98a8-c6070c146ef3",
                            Nombre = "Farid Anabel Trump"
                        },
                        new
                        {
                            Id = "b3b04baa-333d-41e4-8a0e-8f584c7078f1",
                            Nombre = "Donald Freddy Uribe"
                        },
                        new
                        {
                            Id = "b418bdd3-6bf1-4f7d-8e76-51b755d3a0c2",
                            Nombre = "Alba Teodoro Toledo"
                        },
                        new
                        {
                            Id = "b83df56a-7258-436f-bc2f-4da90e6d8f37",
                            Nombre = "Alba Freddy Herrera"
                        },
                        new
                        {
                            Id = "b8c78c7f-48cf-4d48-96a3-7e16259c2b17",
                            Nombre = "Donald Teodoro Trump"
                        },
                        new
                        {
                            Id = "b96492e8-18fa-409b-a405-f5af8d280215",
                            Nombre = "Felipa Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "b9a84689-8d60-46f7-8a56-9a6d772624e4",
                            Nombre = "Eusebio Anabel Herrera"
                        },
                        new
                        {
                            Id = "b9ce651e-a9ff-49bd-b892-4cf78ba1edb8",
                            Nombre = "Donald Anabel Trump"
                        },
                        new
                        {
                            Id = "b9e69b42-e964-42f4-98ec-85dc062f724e",
                            Nombre = "Alba Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "ba44c717-07c2-49e1-ae92-6dc04eb21621",
                            Nombre = "Donald Rick Toledo"
                        },
                        new
                        {
                            Id = "ba5cb5b9-514b-4647-85c5-5a37d46b955c",
                            Nombre = "Felipa Nicomedes Trump"
                        },
                        new
                        {
                            Id = "ba904d9e-391b-417d-9476-6242636b29d5",
                            Nombre = "Nicolás Rick Ruiz"
                        },
                        new
                        {
                            Id = "bb34f505-676b-42bf-a6ad-da6a3220ac37",
                            Nombre = "Alba Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "bb51d180-185b-46f2-b1bf-9cc69b5e9090",
                            Nombre = "Nicolás Rick Maduro"
                        },
                        new
                        {
                            Id = "bd6d2266-d7de-416a-852a-32f499e4a097",
                            Nombre = "Donald Rick Trump"
                        },
                        new
                        {
                            Id = "be2d14e8-c363-4592-9f4b-00302d163449",
                            Nombre = "Nicolás Silvana Maduro"
                        },
                        new
                        {
                            Id = "be549093-7b6d-413a-88fe-163a81e9355a",
                            Nombre = "Alba Murty Maduro"
                        },
                        new
                        {
                            Id = "beb85e93-1e2c-4e0e-a6a0-dbc19c48e0eb",
                            Nombre = "Alvaro Rick Toledo"
                        },
                        new
                        {
                            Id = "c063d5da-f7e4-4ca8-a7fd-41eaab2fb5e5",
                            Nombre = "Felipa Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "c08b9c23-00d8-443a-8264-05d566470aa7",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "c1954ba4-4aa2-436d-9396-a940a1aeea23",
                            Nombre = "Nicolás Freddy Herrera"
                        },
                        new
                        {
                            Id = "c2218c1e-1cce-42a6-9264-456ea7e94045",
                            Nombre = "Donald Freddy Ruiz"
                        },
                        new
                        {
                            Id = "c4c770eb-7eaa-410e-8bd0-42da78029bf5",
                            Nombre = "Farid Rick Toledo"
                        },
                        new
                        {
                            Id = "c5726163-161a-4215-933b-2c4dea56c2ab",
                            Nombre = "Alvaro Silvana Maduro"
                        },
                        new
                        {
                            Id = "c62a8b72-2f0e-4a42-81d8-9128e77fc88f",
                            Nombre = "Eusebio Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "c632e341-1dc7-4de6-b6a2-c8cf0e7b2d87",
                            Nombre = "Alba Anabel Toledo"
                        },
                        new
                        {
                            Id = "c67cb101-96e7-422a-8a5e-386e16fe7f3a",
                            Nombre = "Alba Freddy Toledo"
                        },
                        new
                        {
                            Id = "c75ed53b-27ce-48c0-a9a7-7859b67faca1",
                            Nombre = "Alvaro Anabel Trump"
                        },
                        new
                        {
                            Id = "c80a89ab-04c4-49bd-8854-20e4b0818949",
                            Nombre = "Donald Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "c839f197-6ed2-41a6-af1a-cccea8b7f37d",
                            Nombre = "Felipa Freddy Trump"
                        },
                        new
                        {
                            Id = "c83b5989-b664-453a-8046-30d1a7e24519",
                            Nombre = "Alvaro Teodoro Uribe"
                        },
                        new
                        {
                            Id = "c9c4da2d-23ec-488d-bbd8-36dd4b0bb261",
                            Nombre = "Donald Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "ca322214-8d2b-4a0c-9148-54711e2b7a73",
                            Nombre = "Eusebio Freddy Herrera"
                        },
                        new
                        {
                            Id = "cb22343e-7d93-46cc-b269-7ec5a3fac203",
                            Nombre = "Farid Murty Uribe"
                        },
                        new
                        {
                            Id = "cb5eb742-e779-41ca-87b3-798964007f65",
                            Nombre = "Eusebio Rick Toledo"
                        },
                        new
                        {
                            Id = "cbd36330-464d-441e-9150-6eed3b1c0353",
                            Nombre = "Eusebio Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "cc4853a8-e6c4-4ecd-9acf-63b5d75c3e11",
                            Nombre = "Alvaro Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "cc87b477-a385-4c91-977d-48fc449ca5dd",
                            Nombre = "Alba Rick Ruiz"
                        },
                        new
                        {
                            Id = "cce9ce2f-09bf-4392-9a21-130dc5084186",
                            Nombre = "Felipa Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "cd2e4445-b953-4a63-ac6a-ca6d2bb0b0f8",
                            Nombre = "Nicolás Teodoro Uribe"
                        },
                        new
                        {
                            Id = "cd617c55-cd49-4084-8193-53d34875a113",
                            Nombre = "Alvaro Rick Herrera"
                        },
                        new
                        {
                            Id = "cdad6454-64e9-4e9d-9264-01c7f7bff222",
                            Nombre = "Farid Anabel Ruiz"
                        },
                        new
                        {
                            Id = "cdedeb7c-488a-469f-b2e7-d232d35b861f",
                            Nombre = "Alba Anabel Herrera"
                        },
                        new
                        {
                            Id = "ce16fc1c-3707-45ed-9695-bf1c30ccb219",
                            Nombre = "Felipa Rick Toledo"
                        },
                        new
                        {
                            Id = "ce4378a7-cda5-43aa-a1f1-4a0db54e2f92",
                            Nombre = "Alba Rick Trump"
                        },
                        new
                        {
                            Id = "cf490f8e-ad69-4337-b937-17a4467cc11c",
                            Nombre = "Alba Murty Trump"
                        },
                        new
                        {
                            Id = "cf6aaad1-8389-46e6-b295-1ddfcfaf827b",
                            Nombre = "Eusebio Murty Uribe"
                        },
                        new
                        {
                            Id = "d03c8cca-3af9-4505-ba53-84971369dd90",
                            Nombre = "Nicolás Diomedes Toledo"
                        },
                        new
                        {
                            Id = "d0547a09-0ec2-4751-9d8e-fa164095d810",
                            Nombre = "Eusebio Silvana Ruiz"
                        },
                        new
                        {
                            Id = "d06848dd-7943-4848-be86-f5f6f90608a6",
                            Nombre = "Farid Murty Herrera"
                        },
                        new
                        {
                            Id = "d0689873-3ade-4fbb-8854-2aacba95d26a",
                            Nombre = "Felipa Silvana Toledo"
                        },
                        new
                        {
                            Id = "d15e7bdf-cab5-4646-8611-1bba6dece998",
                            Nombre = "Eusebio Teodoro Herrera"
                        },
                        new
                        {
                            Id = "d2dbbe7e-0b18-47b5-94c2-ca991004c420",
                            Nombre = "Felipa Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "d415b2a8-df59-442f-b773-89867f3b6a82",
                            Nombre = "Farid Rick Ruiz"
                        },
                        new
                        {
                            Id = "d7a49cb4-5a95-4b87-8aec-0110e351a3b6",
                            Nombre = "Eusebio Anabel Uribe"
                        },
                        new
                        {
                            Id = "d7d4fdf7-0aa4-4fe6-aa3d-77e503b934c8",
                            Nombre = "Nicolás Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "d864ee0b-e4c4-4173-a841-4b6df3b05988",
                            Nombre = "Alba Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "daafb4a6-b4a7-44b1-b376-d34caa0a9c86",
                            Nombre = "Felipa Murty Trump"
                        },
                        new
                        {
                            Id = "dc0cf06a-f40d-49b9-82ce-515235adaa20",
                            Nombre = "Nicolás Rick Herrera"
                        },
                        new
                        {
                            Id = "dc2952e7-22b5-4c7c-b594-8feccf8f6589",
                            Nombre = "Donald Diomedes Toledo"
                        },
                        new
                        {
                            Id = "dca186eb-274b-48ae-87f6-e144226cbc7c",
                            Nombre = "Eusebio Rick Maduro"
                        },
                        new
                        {
                            Id = "dd61d081-48f3-4aec-aadb-21b7a512b2a0",
                            Nombre = "Eusebio Diomedes Herrera"
                        },
                        new
                        {
                            Id = "e0a62c1e-d05d-4578-974a-00ec7e6d6276",
                            Nombre = "Nicolás Diomedes Trump"
                        },
                        new
                        {
                            Id = "e17d4afa-d615-4dc9-920e-9f40ba9f1f34",
                            Nombre = "Alba Anabel Ruiz"
                        },
                        new
                        {
                            Id = "e22c82c6-c24d-41ff-afe7-169bb96c20e8",
                            Nombre = "Farid Freddy Herrera"
                        },
                        new
                        {
                            Id = "e29d3719-150c-4648-9e9b-74c035a24f2c",
                            Nombre = "Farid Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "e388cfc4-b105-4e15-b811-9cad3ad6092e",
                            Nombre = "Alvaro Silvana Herrera"
                        },
                        new
                        {
                            Id = "e43d7f28-f395-4cf6-8cde-5dcaafa005b2",
                            Nombre = "Donald Murty Maduro"
                        },
                        new
                        {
                            Id = "e534792f-ec40-4ba5-8224-3d7bbb8e0245",
                            Nombre = "Nicolás Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "e6ac7527-fde7-4351-9cc6-5168a37456b3",
                            Nombre = "Donald Anabel Uribe"
                        },
                        new
                        {
                            Id = "e7bd8a56-edc8-4d4c-b813-a2fbdc225ca7",
                            Nombre = "Donald Anabel Maduro"
                        },
                        new
                        {
                            Id = "e9960fd0-e072-4b27-87d0-e82a694c1e74",
                            Nombre = "Alba Anabel Maduro"
                        },
                        new
                        {
                            Id = "ea50f773-abec-4d70-9a7d-35cd922f9673",
                            Nombre = "Nicolás Rick Toledo"
                        },
                        new
                        {
                            Id = "ec4ef452-4c27-4bca-b8a5-1970d80daeb3",
                            Nombre = "Donald Anabel Toledo"
                        },
                        new
                        {
                            Id = "ec8504c4-7b9b-4bd3-a7f7-3b0dfc57b9ba",
                            Nombre = "Alvaro Murty Toledo"
                        },
                        new
                        {
                            Id = "ee6dd59c-c250-42db-8ba1-e786c6422726",
                            Nombre = "Alba Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "ef8de692-b841-46da-b5bf-93364a3ebcd3",
                            Nombre = "Farid Nicomedes Trump"
                        },
                        new
                        {
                            Id = "eff0c871-06f6-4945-9753-1cb44f78a6cc",
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            Id = "f050eaaa-c44f-41da-bc32-3e6ed9683963",
                            Nombre = "Eusebio Murty Maduro"
                        },
                        new
                        {
                            Id = "f0559165-f8eb-46fc-ab4e-b8ac9f2683f4",
                            Nombre = "Alvaro Diomedes Maduro"
                        },
                        new
                        {
                            Id = "f0d5976e-9e97-44ff-b062-857892da564d",
                            Nombre = "Eusebio Teodoro Uribe"
                        },
                        new
                        {
                            Id = "f1b8ad48-6948-49bd-b7fe-d79891e7afe1",
                            Nombre = "Donald Rick Sarmiento"
                        },
                        new
                        {
                            Id = "f1eb3327-3c49-41a3-95a5-038f0efc84f1",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "f23c8b5b-0ac4-43a7-ac66-7f4ae2f94ac1",
                            Nombre = "Eusebio Murty Herrera"
                        },
                        new
                        {
                            Id = "f2af2c73-2ff9-4752-8f07-55b691d42cb4",
                            Nombre = "Farid Teodoro Toledo"
                        },
                        new
                        {
                            Id = "f381e84b-8f78-474d-b777-ee4556f399ec",
                            Nombre = "Alvaro Rick Sarmiento"
                        },
                        new
                        {
                            Id = "f480624d-35d7-4751-9a9e-ea098c7357c0",
                            Nombre = "Eusebio Silvana Maduro"
                        },
                        new
                        {
                            Id = "f4a1fccd-e6c7-4e40-a8c4-4defc08eb505",
                            Nombre = "Alvaro Diomedes Toledo"
                        },
                        new
                        {
                            Id = "f5adea1a-08aa-44f0-8079-dfd92e6bebef",
                            Nombre = "Donald Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "f5b5f8ce-41f3-4aed-9b92-fc8f7dac143f",
                            Nombre = "Alba Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "f6065e42-794e-4465-a256-3065c5352513",
                            Nombre = "Eusebio Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "f6c81e07-4a60-40fe-a2f7-cb6f3130fd95",
                            Nombre = "Farid Teodoro Uribe"
                        },
                        new
                        {
                            Id = "f6f19ccb-8f4b-4887-9a89-98e56132dbd2",
                            Nombre = "Farid Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "f7188c55-db4f-4e39-8890-ad289c8af2c2",
                            Nombre = "Alvaro Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "f86b4eb4-8b79-4a8b-bfd7-8efab1c110e8",
                            Nombre = "Alvaro Silvana Uribe"
                        },
                        new
                        {
                            Id = "f8d1e7c5-54af-4497-b7dd-4863ee08c0de",
                            Nombre = "Donald Freddy Trump"
                        },
                        new
                        {
                            Id = "f8e7fcfc-5b2f-4f0e-8294-bedd41847614",
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            Id = "fa320238-137b-49e6-99b1-a78c381ed671",
                            Nombre = "Farid Diomedes Herrera"
                        },
                        new
                        {
                            Id = "fae159f4-ee72-4875-a4a6-82babac6fd10",
                            Nombre = "Donald Rick Herrera"
                        },
                        new
                        {
                            Id = "fb469a85-e7f2-4f7b-90c9-d196387519a5",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "fbf176f2-89fd-421c-8bbe-1b026716831c",
                            Nombre = "Felipa Silvana Ruiz"
                        },
                        new
                        {
                            Id = "fc495d0b-fd87-4477-a8b6-fb8352041a47",
                            Nombre = "Farid Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "fc5c758f-509e-464d-b18e-489896847016",
                            Nombre = "Eusebio Diomedes Maduro"
                        },
                        new
                        {
                            Id = "fde86671-6d18-4d56-8b34-786472be4912",
                            Nombre = "Alvaro Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "ff8c760e-bf75-4558-81b3-4a887b1cebc0",
                            Nombre = "Nicolás Silvana Herrera"
                        },
                        new
                        {
                            Id = "ffce1589-fa85-4010-808b-2a777f818c46",
                            Nombre = "Alba Silvana Maduro"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = "187512f0-568a-48e0-afd0-54f7f1956e2c",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "9ae5f0d2-b2a9-4c14-8ede-726e2fdca6cf",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "2c12ec0c-4616-4d5f-8a40-7a7914531bed",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "5a802d72-f903-42bf-a5ec-bb9cd073f61e",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "359e8a89-d2ac-4e5e-a7ef-15bb92a4b279",
                            Nombre = "Programacion"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dirección")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscuelaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AñoDeCreación")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEscuela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = "c3e7ca49-64e6-4246-84b7-c6400fd6511f",
                            AñoDeCreación = 2005,
                            Ciudad = " Bogota",
                            Dirección = " Avda siempre viva",
                            Nombre = " Platzi School",
                            Pais = " Colombia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AsignaturaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Escuela", null)
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platzi_ASP_NET_CORE.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
