// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Platzi_ASP_NET_CORE.Models;

#nullable disable

namespace Platzi_ASP_NET_CORE.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20220525144906_ManyToMany")]
    partial class ManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = "0035f3a1-8fa9-4e3f-86da-29f43637c6a0",
                            Nombre = "Alvaro Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "00527ce6-1df6-4f0c-ab47-505587dff9b8",
                            Nombre = "Donald Murty Trump"
                        },
                        new
                        {
                            Id = "005a4902-ff10-496c-8173-e6387c0524fc",
                            Nombre = "Alvaro Freddy Herrera"
                        },
                        new
                        {
                            Id = "00d87109-09cb-4dab-bc0e-b6503b7f12cd",
                            Nombre = "Nicolás Murty Uribe"
                        },
                        new
                        {
                            Id = "013957a3-aa9d-4ef7-a1f7-bec1e9106a27",
                            Nombre = "Donald Freddy Ruiz"
                        },
                        new
                        {
                            Id = "01ac8868-4d28-4fee-8d10-bfdc50667e32",
                            Nombre = "Nicolás Murty Ruiz"
                        },
                        new
                        {
                            Id = "01c0ab5c-c852-4c11-b804-b1035c123450",
                            Nombre = "Farid Anabel Toledo"
                        },
                        new
                        {
                            Id = "026e1b42-b434-49e8-9bfb-b4a7acb298d8",
                            Nombre = "Alvaro Rick Herrera"
                        },
                        new
                        {
                            Id = "036479b2-168d-4093-9b41-7457e7ef5b8c",
                            Nombre = "Felipa Murty Toledo"
                        },
                        new
                        {
                            Id = "036f3269-e212-4008-80b7-85c168a089f6",
                            Nombre = "Alba Anabel Maduro"
                        },
                        new
                        {
                            Id = "037090c3-9646-4bb6-988a-81aa141f9599",
                            Nombre = "Alba Teodoro Uribe"
                        },
                        new
                        {
                            Id = "042b7366-dc5b-42bb-aea7-bed42c2f15a9",
                            Nombre = "Alvaro Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "04e8242f-1e95-4a9b-88e1-af2906c3734f",
                            Nombre = "Donald Silvana Maduro"
                        },
                        new
                        {
                            Id = "05878e19-6317-4bd9-8c53-6a92cb9cab57",
                            Nombre = "Farid Silvana Maduro"
                        },
                        new
                        {
                            Id = "06596f15-2ff9-4a26-b02b-b623cef1fd93",
                            Nombre = "Farid Rick Herrera"
                        },
                        new
                        {
                            Id = "0703d70f-2d77-4fb0-b643-0ab56360e7e4",
                            Nombre = "Eusebio Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "07f67398-9a0b-4599-80fa-38e58f559f26",
                            Nombre = "Alba Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "0806f3b3-8fa1-442e-b788-9d8e09a9d23d",
                            Nombre = "Nicolás Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "0ab7fbc8-5988-45ec-b86f-815f9d15660b",
                            Nombre = "Farid Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "0af07f80-3340-4bc4-975c-ac57454086a6",
                            Nombre = "Alba Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "0b5f21a7-24fb-441d-bb9a-d13874ef0271",
                            Nombre = "Donald Diomedes Trump"
                        },
                        new
                        {
                            Id = "0bd2b5ac-addd-437f-99b8-86f74acd1266",
                            Nombre = "Donald Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "0c7edea3-8954-41fe-86c6-7bb1ac0b7406",
                            Nombre = "Felipa Anabel Herrera"
                        },
                        new
                        {
                            Id = "0e3910a0-9c11-44b0-8617-e5f1d290b893",
                            Nombre = "Nicolás Rick Trump"
                        },
                        new
                        {
                            Id = "0e7450b1-b0b8-4412-83b0-4e21e5a54420",
                            Nombre = "Alba Murty Sarmiento"
                        },
                        new
                        {
                            Id = "0f116544-da42-4be8-a30e-7d83e4cc839b",
                            Nombre = "Alvaro Teodoro Maduro"
                        },
                        new
                        {
                            Id = "0fdb5f4a-1969-4d8c-96ba-2fda4e04634d",
                            Nombre = "Eusebio Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "1017427c-673f-4f11-b448-1660e3bbdd0c",
                            Nombre = "Alvaro Freddy Maduro"
                        },
                        new
                        {
                            Id = "10de2786-b7e8-442d-867b-f737bfede2b6",
                            Nombre = "Donald Freddy Uribe"
                        },
                        new
                        {
                            Id = "118b1e68-0b59-46e4-92a7-6e6464d896a3",
                            Nombre = "Alvaro Teodoro Herrera"
                        },
                        new
                        {
                            Id = "120257af-0a69-458f-a379-9c3f5d3fd1ed",
                            Nombre = "Alvaro Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "1291c249-7ad8-4698-baa6-d81200627908",
                            Nombre = "Alvaro Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "13732460-e7af-4470-bf02-9f8060aa2adc",
                            Nombre = "Eusebio Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "140f1cee-f967-45fd-9584-bd8c9161e6ef",
                            Nombre = "Nicolás Rick Sarmiento"
                        },
                        new
                        {
                            Id = "1571ae03-6603-4da9-8479-ce4385b9438f",
                            Nombre = "Alvaro Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "17d3de3d-abb3-4840-9eef-56a1aa21861c",
                            Nombre = "Felipa Murty Ruiz"
                        },
                        new
                        {
                            Id = "17e83f83-1d8d-4c08-b71f-d7b36044077b",
                            Nombre = "Donald Diomedes Maduro"
                        },
                        new
                        {
                            Id = "18319d26-4ff0-403a-8980-27024e8ad16c",
                            Nombre = "Felipa Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "1898eb8d-6c1f-4d40-932d-ae3b8c3ed0de",
                            Nombre = "Nicolás Silvana Uribe"
                        },
                        new
                        {
                            Id = "19c4f458-223b-4dd4-8b23-8e42aed34fe4",
                            Nombre = "Alba Rick Sarmiento"
                        },
                        new
                        {
                            Id = "1a3fc295-9907-450f-99bb-f7746ff714f7",
                            Nombre = "Farid Freddy Maduro"
                        },
                        new
                        {
                            Id = "1ad110ff-aaf5-49f7-8185-f2ebc2423037",
                            Nombre = "Alba Anabel Toledo"
                        },
                        new
                        {
                            Id = "1ae7d8da-288f-477c-a9d9-3e9ee8c2e4dc",
                            Nombre = "Nicolás Silvana Maduro"
                        },
                        new
                        {
                            Id = "1af3f2c4-8b43-41a0-bb0c-28fbaca3201c",
                            Nombre = "Nicolás Rick Toledo"
                        },
                        new
                        {
                            Id = "1d158c61-cdf9-40cf-8f09-f6878626d4a0",
                            Nombre = "Alba Rick Uribe"
                        },
                        new
                        {
                            Id = "1eb5871c-5b88-4a07-9b5d-97eb90161407",
                            Nombre = "Donald Teodoro Trump"
                        },
                        new
                        {
                            Id = "202f8831-d017-4517-9c44-753e90d3a3b1",
                            Nombre = "Eusebio Silvana Toledo"
                        },
                        new
                        {
                            Id = "21404941-1efb-40d3-9fae-515af248a6e0",
                            Nombre = "Alvaro Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "21aa4444-19e6-43e2-bc07-3cf33bb7e669",
                            Nombre = "Felipa Rick Maduro"
                        },
                        new
                        {
                            Id = "22c3588d-18b7-4020-9ea6-192a9ac19cea",
                            Nombre = "Eusebio Murty Sarmiento"
                        },
                        new
                        {
                            Id = "245c05ab-ba09-456a-813a-1f97e8dd19f8",
                            Nombre = "Eusebio Anabel Ruiz"
                        },
                        new
                        {
                            Id = "24d6b521-01e9-4894-942e-9c2360e5f775",
                            Nombre = "Felipa Murty Uribe"
                        },
                        new
                        {
                            Id = "25b21cf7-4a5d-4226-aac5-bb7fcc887710",
                            Nombre = "Felipa Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "2656067f-ac70-4e5e-b99a-ed30276d5d40",
                            Nombre = "Nicolás Diomedes Herrera"
                        },
                        new
                        {
                            Id = "26977017-132e-41e6-8ae6-acb19ca36de3",
                            Nombre = "Eusebio Rick Sarmiento"
                        },
                        new
                        {
                            Id = "27e415b2-27e4-4ebf-8b14-1a491917734d",
                            Nombre = "Felipa Teodoro Herrera"
                        },
                        new
                        {
                            Id = "28dc0b00-9913-4328-a754-cbc7852f28f4",
                            Nombre = "Nicolás Silvana Toledo"
                        },
                        new
                        {
                            Id = "2914debb-a3d1-4e37-ad86-58dc410b2c9f",
                            Nombre = "Donald Anabel Toledo"
                        },
                        new
                        {
                            Id = "29433467-ace6-448c-a39e-33bfdf52a5f4",
                            Nombre = "Eusebio Rick Ruiz"
                        },
                        new
                        {
                            Id = "29d4d2a6-a675-4ff3-9977-f1efc001c136",
                            Nombre = "Felipa Diomedes Trump"
                        },
                        new
                        {
                            Id = "29de73af-23ab-4d9c-a623-7412c9ae8fc8",
                            Nombre = "Felipa Teodoro Toledo"
                        },
                        new
                        {
                            Id = "2a37c677-89ec-4690-ab8c-62f3c980d2b8",
                            Nombre = "Alba Murty Ruiz"
                        },
                        new
                        {
                            Id = "2a7edc68-a756-430b-bb34-dc08e347a496",
                            Nombre = "Nicolás Anabel Trump"
                        },
                        new
                        {
                            Id = "2bc41351-38cc-4e4a-93a1-90e07123489d",
                            Nombre = "Alvaro Rick Maduro"
                        },
                        new
                        {
                            Id = "2c642e03-f674-4fe2-bc2d-26b0cc1eb0cf",
                            Nombre = "Felipa Diomedes Herrera"
                        },
                        new
                        {
                            Id = "2d0ac14e-b7fb-4d91-b377-dbf2c5506984",
                            Nombre = "Donald Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "2f46c04a-ea89-4dbf-9f87-c4d80eced97c",
                            Nombre = "Farid Anabel Uribe"
                        },
                        new
                        {
                            Id = "30ae4080-7864-4c71-90fe-a2f19c776363",
                            Nombre = "Eusebio Silvana Maduro"
                        },
                        new
                        {
                            Id = "3103f2ff-f294-4317-b744-20641e2f0687",
                            Nombre = "Alvaro Freddy Toledo"
                        },
                        new
                        {
                            Id = "3127971e-0113-4d06-9d81-449409cbf28d",
                            Nombre = "Donald Nicomedes Trump"
                        },
                        new
                        {
                            Id = "31760700-d880-4577-aa91-02ffff6115c9",
                            Nombre = "Donald Rick Ruiz"
                        },
                        new
                        {
                            Id = "31c8ef10-1e85-4d6b-802d-9286445f1782",
                            Nombre = "Farid Rick Ruiz"
                        },
                        new
                        {
                            Id = "32ffcac9-1aa7-42d4-8454-ce92da2bc6ac",
                            Nombre = "Nicolás Silvana Trump"
                        },
                        new
                        {
                            Id = "334af64d-c59e-48bc-9152-87e57c26aa63",
                            Nombre = "Alvaro Rick Uribe"
                        },
                        new
                        {
                            Id = "3353252c-28b9-47fc-8632-0a82d060f5ab",
                            Nombre = "Eusebio Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "33998599-7859-472f-8e9c-9dfebf2e08df",
                            Nombre = "Alba Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "33d7f7f3-94cf-46e9-9fa4-7e101ee16393",
                            Nombre = "Farid Murty Ruiz"
                        },
                        new
                        {
                            Id = "33d9647d-5680-4698-b4ae-089ea761962f",
                            Nombre = "Donald Rick Herrera"
                        },
                        new
                        {
                            Id = "33fa4635-624d-4945-b64a-299b51497314",
                            Nombre = "Alba Freddy Maduro"
                        },
                        new
                        {
                            Id = "352f11f7-641e-4803-b677-b9f8ce34fc74",
                            Nombre = "Alvaro Teodoro Trump"
                        },
                        new
                        {
                            Id = "352fc45a-b9b4-478a-acbc-15962cc8d25a",
                            Nombre = "Alba Diomedes Trump"
                        },
                        new
                        {
                            Id = "3576c2f2-2d63-4e5e-b830-0f8b4b6c1634",
                            Nombre = "Alba Anabel Herrera"
                        },
                        new
                        {
                            Id = "35b45f16-774d-45d4-92af-cd37efc2fdf5",
                            Nombre = "Nicolás Anabel Toledo"
                        },
                        new
                        {
                            Id = "36d77954-00d5-47d0-88b7-3ca8af7c7667",
                            Nombre = "Eusebio Murty Ruiz"
                        },
                        new
                        {
                            Id = "379d5ba6-823b-4668-b731-b518b5741513",
                            Nombre = "Nicolás Teodoro Toledo"
                        },
                        new
                        {
                            Id = "37de4d81-7392-4cd5-9c2f-092b9550e2ff",
                            Nombre = "Nicolás Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "37e918d2-d55e-477c-ac71-8f20aaea7ff3",
                            Nombre = "Alvaro Murty Uribe"
                        },
                        new
                        {
                            Id = "38e6dc8f-76f8-4827-980e-5662026f4bdd",
                            Nombre = "Alba Teodoro Toledo"
                        },
                        new
                        {
                            Id = "392501d2-7a12-4234-b969-38f8427fdef4",
                            Nombre = "Nicolás Freddy Ruiz"
                        },
                        new
                        {
                            Id = "3a3c9702-6828-4efe-aa5e-5c409c36623e",
                            Nombre = "Felipa Freddy Uribe"
                        },
                        new
                        {
                            Id = "3a3f216f-7f90-41c8-9cae-a384752db2fa",
                            Nombre = "Alvaro Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "3a980ade-c9d8-47b7-9e17-c8e35b1c6a7b",
                            Nombre = "Farid Freddy Uribe"
                        },
                        new
                        {
                            Id = "3b2156b3-af38-4acc-96bc-76c029f3773f",
                            Nombre = "Donald Freddy Toledo"
                        },
                        new
                        {
                            Id = "3ba6cb06-bfdf-43db-8400-cf3e53604439",
                            Nombre = "Eusebio Anabel Trump"
                        },
                        new
                        {
                            Id = "3c654e28-6f1f-431c-9559-ffaf3a69924d",
                            Nombre = "Felipa Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "3c6e4390-1257-4b8a-8358-e87e73b4cc2f",
                            Nombre = "Eusebio Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "3cbc505e-f10a-47a3-8f66-7ed68fd6610c",
                            Nombre = "Nicolás Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "3d4bf7e4-a784-4c15-b954-93c381ceaa46",
                            Nombre = "Eusebio Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "3da51047-3933-43f9-b91c-b1678103b320",
                            Nombre = "Felipa Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "3e028416-c334-4677-8eae-35acf92980a7",
                            Nombre = "Nicolás Freddy Maduro"
                        },
                        new
                        {
                            Id = "3e294346-2822-4bb1-a598-09910f9d0401",
                            Nombre = "Felipa Rick Ruiz"
                        },
                        new
                        {
                            Id = "3f40469c-0f75-4ba0-b5d3-cf561cb07604",
                            Nombre = "Farid Murty Maduro"
                        },
                        new
                        {
                            Id = "3fb8ae50-d23f-4962-98e7-13ebbe02055e",
                            Nombre = "Felipa Diomedes Maduro"
                        },
                        new
                        {
                            Id = "3fee1122-29f6-4bb7-84b1-de2d3bd86054",
                            Nombre = "Eusebio Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "402320fa-9198-46c6-b831-0606cd3876ea",
                            Nombre = "Nicolás Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "403ae626-9511-4c27-9f09-fedf315d10ab",
                            Nombre = "Donald Diomedes Uribe"
                        },
                        new
                        {
                            Id = "4064cef5-fa9d-4692-af6c-0d6054e69124",
                            Nombre = "Alba Rick Trump"
                        },
                        new
                        {
                            Id = "407be297-fbbb-4da3-85a7-05c6b2382d7d",
                            Nombre = "Felipa Silvana Toledo"
                        },
                        new
                        {
                            Id = "408609ca-44a7-41a3-9ab8-7f55bfb7c23a",
                            Nombre = "Nicolás Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "41e29e39-8a83-42d3-a50a-b3d639ee9587",
                            Nombre = "Felipa Silvana Uribe"
                        },
                        new
                        {
                            Id = "4244257c-ffe1-408c-af1d-2a3fb87ef7c7",
                            Nombre = "Eusebio Teodoro Maduro"
                        },
                        new
                        {
                            Id = "42d79e43-6541-4371-9217-a692e1fd9c8c",
                            Nombre = "Donald Anabel Herrera"
                        },
                        new
                        {
                            Id = "43073e9d-bff1-4726-b3df-49fcf2c98354",
                            Nombre = "Eusebio Rick Uribe"
                        },
                        new
                        {
                            Id = "4344c1fa-9e10-46cf-9e08-debe66c7a023",
                            Nombre = "Alvaro Silvana Toledo"
                        },
                        new
                        {
                            Id = "439c4998-dd4e-412a-9618-2e5ae550a728",
                            Nombre = "Alba Silvana Maduro"
                        },
                        new
                        {
                            Id = "443839ea-c8b7-475f-bb32-8e89f3fb4c5c",
                            Nombre = "Farid Rick Sarmiento"
                        },
                        new
                        {
                            Id = "44ea4da2-ea0e-4f65-8ed4-6a5dbffc1b96",
                            Nombre = "Eusebio Diomedes Trump"
                        },
                        new
                        {
                            Id = "44eea1b6-8c5d-458e-80a3-d129fbe9a663",
                            Nombre = "Nicolás Diomedes Maduro"
                        },
                        new
                        {
                            Id = "4603f00a-469b-4063-bd55-a9b01ad95ead",
                            Nombre = "Alba Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "46d4dedc-76e0-4f6d-aa65-3305cbb6add5",
                            Nombre = "Nicolás Teodoro Trump"
                        },
                        new
                        {
                            Id = "46e3d8c4-5295-4323-aa56-4bb70cf54b13",
                            Nombre = "Donald Diomedes Herrera"
                        },
                        new
                        {
                            Id = "4751c49b-fed8-4d5f-b3ca-7715a29bc4e8",
                            Nombre = "Farid Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "49ec6315-7986-4c20-83f3-189656cfdb3e",
                            Nombre = "Nicolás Teodoro Herrera"
                        },
                        new
                        {
                            Id = "4a5d8071-bdf0-447a-bcef-a4e83f24879f",
                            Nombre = "Eusebio Rick Maduro"
                        },
                        new
                        {
                            Id = "4a8fccb2-466f-4829-b4a4-15f1ec5e1ef1",
                            Nombre = "Farid Diomedes Herrera"
                        },
                        new
                        {
                            Id = "4ac7b77f-66fc-478c-80be-bd72f9515e85",
                            Nombre = "Farid Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "4af167e6-ec22-4b05-9393-7d21790dd295",
                            Nombre = "Farid Anabel Herrera"
                        },
                        new
                        {
                            Id = "4af49e5b-10d8-4f5d-a2e3-f5d6f54ae95e",
                            Nombre = "Eusebio Rick Trump"
                        },
                        new
                        {
                            Id = "4b1b4200-c67e-4ed7-ab2e-91dcfab8c449",
                            Nombre = "Nicolás Silvana Ruiz"
                        },
                        new
                        {
                            Id = "4b9a6649-a659-47eb-8a21-84c6a1882147",
                            Nombre = "Donald Rick Maduro"
                        },
                        new
                        {
                            Id = "4cd18d5f-7647-4d78-8ba5-8bff6755e035",
                            Nombre = "Eusebio Rick Herrera"
                        },
                        new
                        {
                            Id = "4cd39537-be98-4e0f-9568-028894a1f683",
                            Nombre = "Donald Rick Trump"
                        },
                        new
                        {
                            Id = "4cdb75d4-e2c5-4d61-92e3-547e3748fcf6",
                            Nombre = "Alba Freddy Ruiz"
                        },
                        new
                        {
                            Id = "4cdf7b52-592c-4915-b4d4-534546c8d27b",
                            Nombre = "Eusebio Diomedes Toledo"
                        },
                        new
                        {
                            Id = "4d2daa80-9222-45f0-af18-a5532e33922c",
                            Nombre = "Farid Freddy Toledo"
                        },
                        new
                        {
                            Id = "4e027e69-6c23-44a7-b524-a0d6b5eb115f",
                            Nombre = "Alba Freddy Toledo"
                        },
                        new
                        {
                            Id = "4e218d8a-3d58-4974-9060-b6e8a7813d03",
                            Nombre = "Alvaro Murty Trump"
                        },
                        new
                        {
                            Id = "4f1e8057-2a4d-4e3a-a8b8-0476e7db33e0",
                            Nombre = "Felipa Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "4f690cbe-38c0-4426-8177-9939a29d52ad",
                            Nombre = "Alvaro Teodoro Toledo"
                        },
                        new
                        {
                            Id = "4fc08937-9cde-42e3-b979-a61a1e7d05c5",
                            Nombre = "Alba Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "4ff35a10-f957-40da-a9a7-97d3cd5a7e7e",
                            Nombre = "Alba Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "510fa694-f7a8-4421-89c2-7a90fa017e82",
                            Nombre = "Alba Nicomedes Trump"
                        },
                        new
                        {
                            Id = "51945e57-5723-4c4d-b63f-3b84f4a83f8f",
                            Nombre = "Alvaro Silvana Uribe"
                        },
                        new
                        {
                            Id = "51973934-d25a-4679-a66b-6e51d67fefa1",
                            Nombre = "Felipa Teodoro Maduro"
                        },
                        new
                        {
                            Id = "51b9864c-326d-4b0e-9b24-58cfef9d592b",
                            Nombre = "Eusebio Rick Toledo"
                        },
                        new
                        {
                            Id = "52ac57e8-30de-47b3-8c81-0df14ca9364f",
                            Nombre = "Alba Freddy Uribe"
                        },
                        new
                        {
                            Id = "52cd4eae-acf3-49d2-833e-6349c571c717",
                            Nombre = "Farid Murty Sarmiento"
                        },
                        new
                        {
                            Id = "534a64af-778d-471c-a04b-0d14f9cf7e8d",
                            Nombre = "Nicolás Murty Maduro"
                        },
                        new
                        {
                            Id = "538da1de-d90d-4e3b-829d-1f4015c32954",
                            Nombre = "Eusebio Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "541dfee0-7ecf-4732-ae61-b0ababceba02",
                            Nombre = "Donald Silvana Uribe"
                        },
                        new
                        {
                            Id = "54b66f45-b6cb-464c-9c1f-f579c822b291",
                            Nombre = "Nicolás Rick Ruiz"
                        },
                        new
                        {
                            Id = "560f6798-1af6-45f2-a5cb-611bdb75261d",
                            Nombre = "Alvaro Anabel Ruiz"
                        },
                        new
                        {
                            Id = "5755186f-750e-4f0e-9720-e767a740f66e",
                            Nombre = "Eusebio Murty Toledo"
                        },
                        new
                        {
                            Id = "57edc33f-366b-4b48-91f0-4231733ae1dc",
                            Nombre = "Felipa Rick Sarmiento"
                        },
                        new
                        {
                            Id = "5816a910-e3e6-4d50-9983-8d6d05c892aa",
                            Nombre = "Farid Silvana Uribe"
                        },
                        new
                        {
                            Id = "587c6a04-3237-45ef-b9ef-2c662a6960df",
                            Nombre = "Alvaro Anabel Toledo"
                        },
                        new
                        {
                            Id = "59626f93-91ba-48ca-bdb7-1795574e5330",
                            Nombre = "Farid Rick Trump"
                        },
                        new
                        {
                            Id = "5980a497-f81b-4561-8a63-c98fbc91d42e",
                            Nombre = "Farid Anabel Trump"
                        },
                        new
                        {
                            Id = "5aa45b27-c9fe-4155-ab01-f6acfd2e6fee",
                            Nombre = "Alba Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "5b94ba5a-1882-4517-8740-5bf6107671c5",
                            Nombre = "Farid Freddy Herrera"
                        },
                        new
                        {
                            Id = "5b96c8e0-1084-465e-a534-9ade621f8f05",
                            Nombre = "Alba Murty Trump"
                        },
                        new
                        {
                            Id = "5beec9ba-358e-40dc-9e5e-52af51d5ef18",
                            Nombre = "Alba Diomedes Uribe"
                        },
                        new
                        {
                            Id = "5ca44226-1956-4867-be88-abe9e7380780",
                            Nombre = "Nicolás Murty Herrera"
                        },
                        new
                        {
                            Id = "5cee0686-f2db-4da2-81ed-fdc1453135ed",
                            Nombre = "Eusebio Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "5cf93199-9a90-475b-801f-be162da2b1c7",
                            Nombre = "Alba Silvana Trump"
                        },
                        new
                        {
                            Id = "5d699405-3a0b-4095-b9c8-17799238e90f",
                            Nombre = "Nicolás Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "5eded2c8-3bc9-4635-88e3-562801ced111",
                            Nombre = "Alba Anabel Uribe"
                        },
                        new
                        {
                            Id = "5ee10a3b-8574-445a-b406-96e259f9c514",
                            Nombre = "Alba Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "619d60ed-e248-4355-987e-72ffb385171e",
                            Nombre = "Donald Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "61b8f8f5-a50e-4e10-b62b-5d58a13c9c1f",
                            Nombre = "Alba Murty Toledo"
                        },
                        new
                        {
                            Id = "61ef6f06-e594-493d-b709-a475d5f02fdf",
                            Nombre = "Donald Freddy Maduro"
                        },
                        new
                        {
                            Id = "6308ca4b-0a7a-465f-8249-d680ab54bf85",
                            Nombre = "Alba Anabel Trump"
                        },
                        new
                        {
                            Id = "6324b47b-f821-492c-8c33-660e72de58dc",
                            Nombre = "Alvaro Murty Maduro"
                        },
                        new
                        {
                            Id = "63339212-2f37-4c2e-af36-d1fd4de5cc40",
                            Nombre = "Felipa Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "6426e249-93ab-49dc-82e6-35f8412b8d69",
                            Nombre = "Farid Diomedes Toledo"
                        },
                        new
                        {
                            Id = "6506c432-39c9-4e45-a9e7-13aa89dfe085",
                            Nombre = "Donald Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "665a367a-0216-45b5-b985-79b290c474e3",
                            Nombre = "Nicolás Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "6722d6f7-1251-462d-93a1-f940185962f4",
                            Nombre = "Farid Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "674a2444-c3a6-433f-adae-bdd7f1571663",
                            Nombre = "Alvaro Murty Herrera"
                        },
                        new
                        {
                            Id = "6798bf94-7014-4bd5-9911-fce0311325f4",
                            Nombre = "Alvaro Diomedes Maduro"
                        },
                        new
                        {
                            Id = "67e64ec0-379b-4ddd-9f93-88933b21f37d",
                            Nombre = "Donald Silvana Toledo"
                        },
                        new
                        {
                            Id = "68a4098a-16b2-46ca-b3e2-8b2df2e6b3d3",
                            Nombre = "Farid Murty Toledo"
                        },
                        new
                        {
                            Id = "68c825d5-4acd-4570-a8ee-84a994781e01",
                            Nombre = "Alvaro Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "690efa64-c99b-402e-a2a6-dad5fea570ad",
                            Nombre = "Felipa Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "696ff96f-45b0-4263-9d3b-359c56e19a27",
                            Nombre = "Farid Murty Uribe"
                        },
                        new
                        {
                            Id = "6b211a05-ff1e-4ce4-83a6-363bbbe23487",
                            Nombre = "Nicolás Freddy Trump"
                        },
                        new
                        {
                            Id = "6b7ac67d-2a00-4662-9dfb-fbf51e932b38",
                            Nombre = "Alba Rick Maduro"
                        },
                        new
                        {
                            Id = "6c93dcac-cc22-497f-abca-814e3e2b9940",
                            Nombre = "Alba Diomedes Herrera"
                        },
                        new
                        {
                            Id = "6d59228a-e5bc-41dc-94ce-63b700aa2e9b",
                            Nombre = "Felipa Murty Maduro"
                        },
                        new
                        {
                            Id = "6dcc3553-8f9d-4e12-9685-d75e36f56da5",
                            Nombre = "Farid Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "6dedf0e4-89e7-4ba2-88a5-fa8735c5783b",
                            Nombre = "Eusebio Silvana Uribe"
                        },
                        new
                        {
                            Id = "6e8b2d2f-e5d8-4487-b992-dfed950136aa",
                            Nombre = "Alvaro Silvana Maduro"
                        },
                        new
                        {
                            Id = "6f08dc8d-4c3e-4288-a538-afea0820658e",
                            Nombre = "Farid Murty Trump"
                        },
                        new
                        {
                            Id = "6f78935e-ad5e-461f-9a57-4a725b424ab1",
                            Nombre = "Alvaro Silvana Ruiz"
                        },
                        new
                        {
                            Id = "6fdedcba-ea6c-4e9f-8073-a6506f502447",
                            Nombre = "Farid Silvana Toledo"
                        },
                        new
                        {
                            Id = "7090846a-8f9e-4c96-aee6-844cdbc1d6fb",
                            Nombre = "Farid Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "70a58734-1ccb-41cd-bd52-0c2168b26cb3",
                            Nombre = "Eusebio Diomedes Maduro"
                        },
                        new
                        {
                            Id = "70e333dc-fe5f-4f57-847c-a6abeeb3ad19",
                            Nombre = "Alba Rick Ruiz"
                        },
                        new
                        {
                            Id = "7140de54-4662-47d0-a0f6-eaa53eaa4de9",
                            Nombre = "Donald Anabel Uribe"
                        },
                        new
                        {
                            Id = "7176f00c-1824-43e0-bfed-f33d79ac52f5",
                            Nombre = "Donald Rick Sarmiento"
                        },
                        new
                        {
                            Id = "7203687b-a895-4f0d-b256-2e91fb1bc2bf",
                            Nombre = "Eusebio Murty Maduro"
                        },
                        new
                        {
                            Id = "75509536-296d-4747-9213-f0dd15c2eb63",
                            Nombre = "Eusebio Freddy Toledo"
                        },
                        new
                        {
                            Id = "75adb7d8-6dad-43d1-bb76-e79ee912da06",
                            Nombre = "Felipa Diomedes Uribe"
                        },
                        new
                        {
                            Id = "75eae5c7-7362-4cd0-999f-c6465c0fcd37",
                            Nombre = "Alvaro Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "75f71879-5035-47fb-94f3-f70887315425",
                            Nombre = "Donald Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "765ac633-d334-42fc-8a23-74d21615c6c6",
                            Nombre = "Farid Freddy Trump"
                        },
                        new
                        {
                            Id = "7699f5dd-60d3-4b03-8949-245259b43ebb",
                            Nombre = "Alba Rick Herrera"
                        },
                        new
                        {
                            Id = "76b2eca2-003f-4da5-8606-013bc0e3346e",
                            Nombre = "Felipa Anabel Uribe"
                        },
                        new
                        {
                            Id = "779e992b-5087-4c39-8a88-7b946042b103",
                            Nombre = "Farid Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "7805b6f1-d7de-44f2-a388-13a26f8c187f",
                            Nombre = "Farid Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "78c460f3-7cfb-4964-97a0-e1369a6a7086",
                            Nombre = "Alvaro Diomedes Uribe"
                        },
                        new
                        {
                            Id = "78ccda36-bbd5-43e2-bbd7-23df2708bc4e",
                            Nombre = "Alvaro Silvana Herrera"
                        },
                        new
                        {
                            Id = "7ac200b1-eadc-46b3-9d4a-b248a83ec3d9",
                            Nombre = "Nicolás Silvana Herrera"
                        },
                        new
                        {
                            Id = "7b29dd4c-0fc6-452c-86ee-894368648326",
                            Nombre = "Eusebio Silvana Herrera"
                        },
                        new
                        {
                            Id = "7b342701-fcbc-4ca4-80c7-7cd76e0b4716",
                            Nombre = "Alvaro Anabel Herrera"
                        },
                        new
                        {
                            Id = "7b574357-382b-4c9b-9848-07b466f1ad01",
                            Nombre = "Alba Murty Uribe"
                        },
                        new
                        {
                            Id = "7d10bad0-513b-4bf6-89ac-e618cc6158ac",
                            Nombre = "Donald Diomedes Toledo"
                        },
                        new
                        {
                            Id = "7d6d717e-b0dd-47c8-94dc-855c606eadcb",
                            Nombre = "Eusebio Murty Trump"
                        },
                        new
                        {
                            Id = "7d6e7b36-b9e2-444f-a06b-b7f3a5356c3d",
                            Nombre = "Farid Silvana Herrera"
                        },
                        new
                        {
                            Id = "7e7cddbc-3899-4e82-93da-ca80c55843a1",
                            Nombre = "Alvaro Rick Toledo"
                        },
                        new
                        {
                            Id = "7ed8f163-59df-40cf-bebc-c259ec5098cb",
                            Nombre = "Alvaro Freddy Uribe"
                        },
                        new
                        {
                            Id = "7f929f84-1702-40f6-80a6-49494d7c6ffe",
                            Nombre = "Nicolás Anabel Ruiz"
                        },
                        new
                        {
                            Id = "7f9647cd-4ea3-4a00-b82e-728b700bdcc5",
                            Nombre = "Felipa Anabel Maduro"
                        },
                        new
                        {
                            Id = "807faa05-c26d-455e-8bd4-623033b168d4",
                            Nombre = "Donald Silvana Herrera"
                        },
                        new
                        {
                            Id = "8094f32b-0f8b-4bad-8d66-72d8385f4744",
                            Nombre = "Donald Murty Sarmiento"
                        },
                        new
                        {
                            Id = "81bd4dc1-7c27-4226-828a-4ac0e00bebf9",
                            Nombre = "Eusebio Anabel Toledo"
                        },
                        new
                        {
                            Id = "83cdc890-54b7-4099-abb4-3f286607adb4",
                            Nombre = "Alvaro Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "843453da-f34f-45e6-a357-e8d626a1ff76",
                            Nombre = "Eusebio Anabel Maduro"
                        },
                        new
                        {
                            Id = "8490a864-f674-4bb2-9a26-1aaf826c8b42",
                            Nombre = "Farid Silvana Trump"
                        },
                        new
                        {
                            Id = "84b2fb03-1725-403c-8e6e-7f1ac84949b2",
                            Nombre = "Eusebio Freddy Trump"
                        },
                        new
                        {
                            Id = "85b44397-93a6-4d59-a985-760c5fd81339",
                            Nombre = "Felipa Silvana Herrera"
                        },
                        new
                        {
                            Id = "862848a7-0396-4a48-a226-928446c31b12",
                            Nombre = "Nicolás Teodoro Maduro"
                        },
                        new
                        {
                            Id = "864a04f4-ab56-44a0-a4f3-4bec3c78a191",
                            Nombre = "Felipa Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "8713d77f-2975-4358-9a1c-011aecaa9e14",
                            Nombre = "Nicolás Diomedes Toledo"
                        },
                        new
                        {
                            Id = "8831b0cd-fd5f-4e3c-90cb-f253a22ca59c",
                            Nombre = "Farid Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "88544827-c430-4a37-aeec-afc591fd2700",
                            Nombre = "Alba Silvana Ruiz"
                        },
                        new
                        {
                            Id = "888cd116-ba39-4a01-a929-a2f0ac8bc8d1",
                            Nombre = "Nicolás Anabel Maduro"
                        },
                        new
                        {
                            Id = "89bfa462-e686-4a90-ab79-60a0094ff9a9",
                            Nombre = "Felipa Rick Toledo"
                        },
                        new
                        {
                            Id = "8a6712e7-0ddf-4393-bbfb-245f1c7c1eb9",
                            Nombre = "Donald Murty Toledo"
                        },
                        new
                        {
                            Id = "8a924820-46e7-433f-b6a2-07f96205594e",
                            Nombre = "Donald Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "8b2cd37e-9173-4fbf-93f9-9ce8e17ff08c",
                            Nombre = "Eusebio Anabel Uribe"
                        },
                        new
                        {
                            Id = "8e2023b8-1ad6-429d-ab2c-6b25013fc979",
                            Nombre = "Nicolás Anabel Herrera"
                        },
                        new
                        {
                            Id = "8e414fb3-db12-45c7-85c0-4b3ced72c1f5",
                            Nombre = "Alvaro Rick Trump"
                        },
                        new
                        {
                            Id = "8ee2a80b-4807-4a3c-9adf-05ae5db6d3c5",
                            Nombre = "Alvaro Diomedes Toledo"
                        },
                        new
                        {
                            Id = "8fe89870-c800-429e-b4c9-4915a51ff7e7",
                            Nombre = "Donald Freddy Herrera"
                        },
                        new
                        {
                            Id = "92882c8d-5420-4403-b21e-7065cb0e2891",
                            Nombre = "Alba Anabel Sarmiento"
                        },
                        new
                        {
                            Id = "930145aa-2af5-4095-931a-e2c7cb292752",
                            Nombre = "Alba Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "937d3c3a-55ec-49d7-8499-6fb5bee1f190",
                            Nombre = "Alba Freddy Trump"
                        },
                        new
                        {
                            Id = "93960a2c-8375-461a-83a1-80127de997f5",
                            Nombre = "Alba Murty Maduro"
                        },
                        new
                        {
                            Id = "93d52c12-cbdb-4865-adc5-6bd0c2c01e60",
                            Nombre = "Eusebio Freddy Maduro"
                        },
                        new
                        {
                            Id = "94432b2f-9327-495d-9251-cdcd324af5d9",
                            Nombre = "Eusebio Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "94ecbce7-aa64-4c6d-97e2-71d24f98624d",
                            Nombre = "Felipa Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "957c9e85-e4ca-488f-878b-e7030c518308",
                            Nombre = "Nicolás Freddy Herrera"
                        },
                        new
                        {
                            Id = "960b6af6-3313-49a4-8301-38560f2f6997",
                            Nombre = "Nicolás Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "964f50b3-d7d5-4fe5-851f-d9bfd57711e4",
                            Nombre = "Nicolás Murty Trump"
                        },
                        new
                        {
                            Id = "96be0c64-01cc-4bcd-b0ce-6af717ee77a2",
                            Nombre = "Eusebio Teodoro Toledo"
                        },
                        new
                        {
                            Id = "96d8e9d7-17c3-42c2-83b6-6a632ba6edc4",
                            Nombre = "Felipa Murty Herrera"
                        },
                        new
                        {
                            Id = "96ebc4d6-da1d-4b21-ac5c-d48ad987e85a",
                            Nombre = "Felipa Silvana Ruiz"
                        },
                        new
                        {
                            Id = "97db2775-84b7-4cba-b4fb-241b2df570b1",
                            Nombre = "Alvaro Silvana Trump"
                        },
                        new
                        {
                            Id = "99a6a91d-7d98-4e4e-9814-4a757dedd0b7",
                            Nombre = "Alvaro Rick Ruiz"
                        },
                        new
                        {
                            Id = "9ab4fb36-9d49-4433-a8dc-8201f1fbb3e1",
                            Nombre = "Alba Murty Herrera"
                        },
                        new
                        {
                            Id = "9afbf829-6660-49f8-a979-ef01e20627bd",
                            Nombre = "Alvaro Anabel Trump"
                        },
                        new
                        {
                            Id = "9c185832-87a1-45b7-af89-8e4e1cb9b7c5",
                            Nombre = "Nicolás Freddy Toledo"
                        },
                        new
                        {
                            Id = "9c93aeab-49e4-4bb6-9ecd-6486abb2e3a0",
                            Nombre = "Farid Anabel Maduro"
                        },
                        new
                        {
                            Id = "9ce93980-0aae-4c82-917a-9587cfb0ae00",
                            Nombre = "Felipa Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "9dacd243-f8c1-4ab9-9076-c4057a514231",
                            Nombre = "Alba Rick Toledo"
                        },
                        new
                        {
                            Id = "9f7cac4e-f531-4117-805a-f3e6782161cd",
                            Nombre = "Farid Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "9f885787-6477-4a51-8e09-ef0c15bf87ed",
                            Nombre = "Nicolás Murty Toledo"
                        },
                        new
                        {
                            Id = "9ffa1212-77d7-4a5a-9454-4f660ca8c6fc",
                            Nombre = "Felipa Rick Trump"
                        },
                        new
                        {
                            Id = "a02c3d11-6828-40d2-9961-302eabce39d7",
                            Nombre = "Nicolás Diomedes Trump"
                        },
                        new
                        {
                            Id = "a04201f4-03f9-4ea0-bf5e-d7772b2ff4e4",
                            Nombre = "Alvaro Rick Sarmiento"
                        },
                        new
                        {
                            Id = "a091f341-edec-43cc-85d2-419e0cfc6574",
                            Nombre = "Alvaro Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "a16bf099-070d-41a6-8928-4e8aac64bc21",
                            Nombre = "Felipa Anabel Trump"
                        },
                        new
                        {
                            Id = "a1aff318-feaf-45b6-b611-84825645dd27",
                            Nombre = "Alba Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "a3f21c5d-0565-4146-a573-d9ddf202169a",
                            Nombre = "Alvaro Murty Sarmiento"
                        },
                        new
                        {
                            Id = "a43a3dec-be05-473d-baf1-ddc4380bdf7c",
                            Nombre = "Felipa Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "a451b973-ae30-446d-8789-b0609d8fe6e5",
                            Nombre = "Nicolás Rick Uribe"
                        },
                        new
                        {
                            Id = "a5249f67-35b7-4fa9-be46-e4c6f8bf84e3",
                            Nombre = "Nicolás Diomedes Ruiz"
                        },
                        new
                        {
                            Id = "a5710b9c-9f06-49cb-8dc1-2ef09cfe6554",
                            Nombre = "Eusebio Nicomedes Trump"
                        },
                        new
                        {
                            Id = "a7462862-2116-4e97-ac7d-b073fee12262",
                            Nombre = "Eusebio Diomedes Uribe"
                        },
                        new
                        {
                            Id = "a98c8a9e-e49d-439f-ac31-d5a39f5d19b0",
                            Nombre = "Donald Rick Toledo"
                        },
                        new
                        {
                            Id = "a9989f48-1b00-4eea-8894-79f0cb1eb39a",
                            Nombre = "Farid Rick Uribe"
                        },
                        new
                        {
                            Id = "aa97fa91-cee6-470e-bbeb-a78c90d3c106",
                            Nombre = "Alvaro Freddy Trump"
                        },
                        new
                        {
                            Id = "abb77288-c731-4003-9f1b-a041783a6567",
                            Nombre = "Donald Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "aea906eb-bb40-446e-8e28-65ed24e5d3fa",
                            Nombre = "Felipa Freddy Herrera"
                        },
                        new
                        {
                            Id = "af879dd5-0402-473d-a09d-6c2e94a51a47",
                            Nombre = "Nicolás Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "b26dc24b-1945-44ae-a084-abc62a8658e5",
                            Nombre = "Alvaro Diomedes Herrera"
                        },
                        new
                        {
                            Id = "b33aa86a-8a42-48f4-bb46-7f3592d808e8",
                            Nombre = "Alba Teodoro Herrera"
                        },
                        new
                        {
                            Id = "b3dd6763-ca5a-44bd-ab69-e4e597932e8c",
                            Nombre = "Farid Diomedes Maduro"
                        },
                        new
                        {
                            Id = "b3f742ea-3e2f-469f-b482-a49bb88865b0",
                            Nombre = "Farid Freddy Ruiz"
                        },
                        new
                        {
                            Id = "b4b14d33-cae4-45e6-a098-8a90406467ef",
                            Nombre = "Donald Freddy Trump"
                        },
                        new
                        {
                            Id = "b60ce5b7-42d2-48f5-ab78-1af691a58f9e",
                            Nombre = "Felipa Freddy Ruiz"
                        },
                        new
                        {
                            Id = "b6633afd-d2c5-46a8-a7c6-c19cf2fac98b",
                            Nombre = "Felipa Freddy Maduro"
                        },
                        new
                        {
                            Id = "b69825b8-9188-4f4c-910d-a7e26ddae2d4",
                            Nombre = "Nicolás Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "b6ac39cb-16a5-4edd-8545-13207faf929d",
                            Nombre = "Eusebio Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "b6c58ae6-79ff-4fbd-9b0a-46e8629e8f26",
                            Nombre = "Alba Silvana Herrera"
                        },
                        new
                        {
                            Id = "b7027cf6-e71a-4579-af56-8dc889dde78c",
                            Nombre = "Nicolás Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "b89f4d57-bd59-40f2-8f00-59f837638c60",
                            Nombre = "Alba Teodoro Trump"
                        },
                        new
                        {
                            Id = "b8de49c0-d65f-4e13-9911-e970412eaed5",
                            Nombre = "Farid Diomedes Uribe"
                        },
                        new
                        {
                            Id = "bb2d8fad-8c34-4860-9548-92d9217107dd",
                            Nombre = "Donald Silvana Ruiz"
                        },
                        new
                        {
                            Id = "bda7b380-a5ab-46ec-b194-bd85e5ba8300",
                            Nombre = "Farid Rick Maduro"
                        },
                        new
                        {
                            Id = "be6d4a2e-4e79-496b-b109-e44c6d2e3744",
                            Nombre = "Nicolás Anabel Uribe"
                        },
                        new
                        {
                            Id = "be900f8b-60c3-40a6-a240-74158e7db902",
                            Nombre = "Alba Anabel Ruiz"
                        },
                        new
                        {
                            Id = "be9d1613-962c-47f4-aad3-19829e9f6dc0",
                            Nombre = "Nicolás Freddy Uribe"
                        },
                        new
                        {
                            Id = "bec430a4-55f0-4ba4-ba6f-f5197eb535a3",
                            Nombre = "Donald Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "bf4c1e7a-3df2-4e50-b8be-ef921a1c05da",
                            Nombre = "Farid Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "bfdc059d-ed20-4453-921b-de0dfcfeba0a",
                            Nombre = "Felipa Anabel Toledo"
                        },
                        new
                        {
                            Id = "bff82e0a-77bb-475e-92ae-aff080d87ad0",
                            Nombre = "Donald Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "c09798d5-6f5f-46ab-99e8-7f1460bf1a3d",
                            Nombre = "Eusebio Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "c106a79f-ca3c-4cc5-9ce1-d78e663a6d46",
                            Nombre = "Donald Silvana Sarmiento"
                        },
                        new
                        {
                            Id = "c11ba5e7-9386-4d9d-9470-16953e5152b4",
                            Nombre = "Donald Murty Ruiz"
                        },
                        new
                        {
                            Id = "c281fb5b-6587-4ce5-8d47-cbf4b9c523da",
                            Nombre = "Donald Silvana Trump"
                        },
                        new
                        {
                            Id = "c360503a-5a0c-4a01-bd4d-08df70d87cac",
                            Nombre = "Nicolás Teodoro Uribe"
                        },
                        new
                        {
                            Id = "c3686b3b-c580-41af-a043-fc429dc17809",
                            Nombre = "Alba Diomedes Toledo"
                        },
                        new
                        {
                            Id = "c4ab736c-c4dd-4781-9f97-b7ff30da3e47",
                            Nombre = "Alvaro Anabel Maduro"
                        },
                        new
                        {
                            Id = "c4b91aab-d3ea-438c-bd8d-6d3232b104a9",
                            Nombre = "Eusebio Silvana Ruiz"
                        },
                        new
                        {
                            Id = "c4c2df5e-796d-4bc4-bdb5-050c5f4deabf",
                            Nombre = "Nicolás Diomedes Uribe"
                        },
                        new
                        {
                            Id = "c4c98eab-a7e1-4a23-a644-eae55dff5241",
                            Nombre = "Farid Teodoro Toledo"
                        },
                        new
                        {
                            Id = "c5a2fa78-8509-4a24-a553-140950b784c3",
                            Nombre = "Eusebio Freddy Uribe"
                        },
                        new
                        {
                            Id = "c5a65f1e-e556-4433-8f1e-39eb2a622186",
                            Nombre = "Eusebio Silvana Trump"
                        },
                        new
                        {
                            Id = "c5ccfdec-0459-4b66-af13-699f0c1ae0d6",
                            Nombre = "Nicolás Rick Herrera"
                        },
                        new
                        {
                            Id = "c5ee4a1e-d53d-4121-bca5-8c6a1d82907a",
                            Nombre = "Felipa Nicomedes Trump"
                        },
                        new
                        {
                            Id = "c6008253-3884-4baa-8193-b9a39cecb75f",
                            Nombre = "Nicolás Nicomedes Trump"
                        },
                        new
                        {
                            Id = "c6325219-3476-4847-869c-f2c2fb3b22fe",
                            Nombre = "Alba Freddy Herrera"
                        },
                        new
                        {
                            Id = "c64c8333-51e3-438b-bca4-b07ba2e1bc78",
                            Nombre = "Farid Teodoro Trump"
                        },
                        new
                        {
                            Id = "c6b15959-6ad4-4857-983c-f69d9c0a9cf5",
                            Nombre = "Donald Teodoro Uribe"
                        },
                        new
                        {
                            Id = "c6e7ca27-9bf5-4f1d-9296-c774525db1f6",
                            Nombre = "Alvaro Anabel Uribe"
                        },
                        new
                        {
                            Id = "c6fc0b3c-7b71-40c9-8867-cf59c73f806c",
                            Nombre = "Eusebio Teodoro Herrera"
                        },
                        new
                        {
                            Id = "c74db2c3-467c-4c28-b03f-4f0036215ac8",
                            Nombre = "Alvaro Nicomedes Trump"
                        },
                        new
                        {
                            Id = "c7a8f234-cd96-4e7d-88d1-2cf9b99d90c2",
                            Nombre = "Donald Diomedes Sarmiento"
                        },
                        new
                        {
                            Id = "c7f571a6-c70e-4f50-a8dd-11281e6ffcaa",
                            Nombre = "Alvaro Murty Toledo"
                        },
                        new
                        {
                            Id = "c7fbf358-f497-49f3-9cae-4c89e1d1b564",
                            Nombre = "Donald Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "c8376c40-64c0-4379-8e3b-525e3205b060",
                            Nombre = "Farid Rick Toledo"
                        },
                        new
                        {
                            Id = "c936bf15-4a88-469b-ba3f-70089204d9ff",
                            Nombre = "Farid Teodoro Ruiz"
                        },
                        new
                        {
                            Id = "ca8c352a-1243-4a19-9d0a-f8a070a41a26",
                            Nombre = "Nicolás Murty Sarmiento"
                        },
                        new
                        {
                            Id = "cb51cab9-84b6-47c5-89c3-5d21d17f1eb7",
                            Nombre = "Donald Rick Uribe"
                        },
                        new
                        {
                            Id = "cb9f9aec-aeec-4ebd-863b-c78e794b7f52",
                            Nombre = "Felipa Murty Trump"
                        },
                        new
                        {
                            Id = "ccdce1da-d816-4615-a0c9-d8b401c7abd9",
                            Nombre = "Felipa Freddy Trump"
                        },
                        new
                        {
                            Id = "ce1ca23e-cc59-4909-88ad-cdfd4ec695f4",
                            Nombre = "Eusebio Freddy Ruiz"
                        },
                        new
                        {
                            Id = "ce8fbb50-1c3e-453e-b4f0-502f7d4f1dda",
                            Nombre = "Eusebio Diomedes Herrera"
                        },
                        new
                        {
                            Id = "cf313136-0d2c-4734-a13c-3c853c99460a",
                            Nombre = "Alvaro Diomedes Trump"
                        },
                        new
                        {
                            Id = "d0141397-c564-4716-8c8f-aae0b67ae332",
                            Nombre = "Donald Teodoro Toledo"
                        },
                        new
                        {
                            Id = "d01648cc-ea5f-410c-ab2b-9be4fc573459",
                            Nombre = "Donald Anabel Trump"
                        },
                        new
                        {
                            Id = "d066f085-61b1-41b2-b02a-c5d430e8414b",
                            Nombre = "Donald Murty Maduro"
                        },
                        new
                        {
                            Id = "d13ef516-ed8c-40eb-9c06-60460ca341e9",
                            Nombre = "Felipa Nicomedes Uribe"
                        },
                        new
                        {
                            Id = "d14e4f0a-630e-460e-bdbc-f1d07dc2e85b",
                            Nombre = "Felipa Murty Sarmiento"
                        },
                        new
                        {
                            Id = "d2908cf3-842f-4d6b-a4bf-a3516754bf25",
                            Nombre = "Alba Silvana Uribe"
                        },
                        new
                        {
                            Id = "d2b0ceb9-9ecd-4013-99ad-3a2705c94e10",
                            Nombre = "Felipa Diomedes Toledo"
                        },
                        new
                        {
                            Id = "d2c16f77-97e8-4a62-a110-681169767b63",
                            Nombre = "Alvaro Murty Ruiz"
                        },
                        new
                        {
                            Id = "d2ffe8fe-0130-42d9-8592-5debbb44a497",
                            Nombre = "Farid Teodoro Maduro"
                        },
                        new
                        {
                            Id = "d33ba563-98fa-44e9-8080-6132b57ab924",
                            Nombre = "Alba Teodoro Maduro"
                        },
                        new
                        {
                            Id = "d3adb63d-8727-450e-81ef-b5abbff87f4c",
                            Nombre = "Donald Murty Uribe"
                        },
                        new
                        {
                            Id = "d44bebff-96fd-4929-afcd-bc86b815e9b7",
                            Nombre = "Eusebio Teodoro Uribe"
                        },
                        new
                        {
                            Id = "d50c5a40-34a9-46dc-abba-5b12c1e1c5ad",
                            Nombre = "Farid Silvana Ruiz"
                        },
                        new
                        {
                            Id = "d5951272-6c0c-4cd2-aef0-3146ce0193cc",
                            Nombre = "Alvaro Teodoro Sarmiento"
                        },
                        new
                        {
                            Id = "d78546a2-ed12-48bd-ad2a-bf5abe56e590",
                            Nombre = "Alba Silvana Toledo"
                        },
                        new
                        {
                            Id = "d94dcb82-8176-4d56-81b7-da5e46a29e18",
                            Nombre = "Eusebio Anabel Herrera"
                        },
                        new
                        {
                            Id = "da04b533-64e2-45b6-87fa-f64f790336cf",
                            Nombre = "Donald Teodoro Herrera"
                        },
                        new
                        {
                            Id = "da353755-d1c4-4052-bd8e-1073fc2d1042",
                            Nombre = "Felipa Rick Uribe"
                        },
                        new
                        {
                            Id = "dd585936-badf-4e98-84be-2748410f1644",
                            Nombre = "Alba Diomedes Maduro"
                        },
                        new
                        {
                            Id = "deb71be0-ba20-406f-9745-cea589314ef4",
                            Nombre = "Donald Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "df3edb2a-3906-43f0-ae68-58f8635e1a93",
                            Nombre = "Alvaro Nicomedes Toledo"
                        },
                        new
                        {
                            Id = "dff734c8-a7b6-43df-8c03-6e6fcd7ddf73",
                            Nombre = "Eusebio Murty Uribe"
                        },
                        new
                        {
                            Id = "e1bd9173-9549-4ee5-a446-454c484b4547",
                            Nombre = "Farid Teodoro Herrera"
                        },
                        new
                        {
                            Id = "e219e20e-881f-4c63-b1fd-18fb314e4f00",
                            Nombre = "Felipa Anabel Ruiz"
                        },
                        new
                        {
                            Id = "e48e9184-f668-4a9d-871c-4b51d323b549",
                            Nombre = "Felipa Silvana Trump"
                        },
                        new
                        {
                            Id = "e57d8719-04cd-4fa8-a0cc-b3d9803ccbb1",
                            Nombre = "Felipa Silvana Maduro"
                        },
                        new
                        {
                            Id = "e5cefa17-f041-4841-97d4-5dfbff2601b5",
                            Nombre = "Donald Murty Herrera"
                        },
                        new
                        {
                            Id = "e5d19c0c-ef06-41e9-bc9d-d7fd5dfe33f2",
                            Nombre = "Alba Freddy Sarmiento"
                        },
                        new
                        {
                            Id = "e6422974-4c42-43f1-829d-47020e5568d7",
                            Nombre = "Donald Anabel Ruiz"
                        },
                        new
                        {
                            Id = "e85b9534-28d2-43e6-a8da-acc8e9f7ac74",
                            Nombre = "Nicolás Rick Maduro"
                        },
                        new
                        {
                            Id = "e8ccea08-fafc-4808-8af8-13a4a3ecf2d4",
                            Nombre = "Farid Murty Herrera"
                        },
                        new
                        {
                            Id = "ea45685e-612c-44c2-ac85-3a2a690ebdc6",
                            Nombre = "Farid Nicomedes Ruiz"
                        },
                        new
                        {
                            Id = "eb1ac131-d6a9-4671-ab3a-543c09c0680a",
                            Nombre = "Felipa Teodoro Uribe"
                        },
                        new
                        {
                            Id = "ed6fd5ed-aa4f-48c6-a7e1-4cca8eb77b68",
                            Nombre = "Felipa Teodoro Trump"
                        },
                        new
                        {
                            Id = "ee06c962-55ed-4190-8a5c-425c290ae980",
                            Nombre = "Eusebio Freddy Herrera"
                        },
                        new
                        {
                            Id = "ef260547-2c4b-46da-ae5a-71eaa20aee9a",
                            Nombre = "Alvaro Freddy Ruiz"
                        },
                        new
                        {
                            Id = "ef9cfec0-708f-471f-9e73-36232120e39e",
                            Nombre = "Nicolás Nicomedes Herrera"
                        },
                        new
                        {
                            Id = "f1693108-181e-44a3-9a1e-dcacaec9fdaf",
                            Nombre = "Farid Nicomedes Trump"
                        },
                        new
                        {
                            Id = "f1fb2628-dbe5-4e93-b65d-eff3301fab1b",
                            Nombre = "Eusebio Murty Herrera"
                        },
                        new
                        {
                            Id = "f5731b73-fe33-4ba4-a446-09b614fd9b98",
                            Nombre = "Alvaro Teodoro Uribe"
                        },
                        new
                        {
                            Id = "f65efe26-4009-427c-8b46-f4c996281863",
                            Nombre = "Donald Teodoro Maduro"
                        },
                        new
                        {
                            Id = "f69b7149-1fc8-4def-baed-907640d47e49",
                            Nombre = "Felipa Nicomedes Maduro"
                        },
                        new
                        {
                            Id = "f6bc66a9-5d57-49f7-806c-25ad7b2d7962",
                            Nombre = "Felipa Rick Herrera"
                        },
                        new
                        {
                            Id = "f9566ec7-266a-4a33-b508-1b7c4e56ac6e",
                            Nombre = "Alba Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "fad01732-cdcb-4ea4-8d18-cb79636420e6",
                            Nombre = "Farid Teodoro Uribe"
                        },
                        new
                        {
                            Id = "fb4d0b81-1659-448e-bddf-c7f2780c7a1f",
                            Nombre = "Eusebio Teodoro Trump"
                        },
                        new
                        {
                            Id = "fda4ca33-9151-4436-8bdd-220a0c292009",
                            Nombre = "Eusebio Nicomedes Sarmiento"
                        },
                        new
                        {
                            Id = "fe0809d9-ac28-48dc-8233-cac8b71c84c9",
                            Nombre = "Donald Anabel Maduro"
                        },
                        new
                        {
                            Id = "fe3120b0-db5e-4e64-8d92-fb5053f9eac1",
                            Nombre = "Farid Diomedes Trump"
                        },
                        new
                        {
                            Id = "ff360767-6883-4937-a35f-f5d35bd8feff",
                            Nombre = "Felipa Freddy Toledo"
                        },
                        new
                        {
                            Id = "ff814585-30e9-40b2-b4f0-f14fa7c2e1e8",
                            Nombre = "Farid Anabel Ruiz"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CursoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = "6f153ad3-46e5-44bb-b91c-c74764fcf3af",
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            Id = "4d741487-6bc2-4cbd-9d85-a51bc1aa9599",
                            Nombre = "Educación Física"
                        },
                        new
                        {
                            Id = "8699fc7c-a39f-4982-a1ce-6cd596599bf8",
                            Nombre = "Castellano"
                        },
                        new
                        {
                            Id = "d4602433-d64c-4429-befb-6986333ea811",
                            Nombre = "Ciencias Naturales"
                        },
                        new
                        {
                            Id = "46c8d3c4-4599-453e-860c-16afd50daab9",
                            Nombre = "Programacion"
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dirección")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscuelaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Jornada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AñoDeCreación")
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEscuela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = "21d6e138-eb0e-4d68-bdfd-284f3d886d83",
                            AñoDeCreación = 2005,
                            Ciudad = " Bogota",
                            Dirección = " Avda siempre viva",
                            Nombre = " Platzi School",
                            Pais = " Colombia",
                            TipoEscuela = 1
                        });
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlumnoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AsignaturaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Asignatura", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Curso", null)
                        .WithMany("Asignaturas")
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Escuela", null)
                        .WithMany("Cursos")
                        .HasForeignKey("EscuelaId");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Evaluación", b =>
                {
                    b.HasOne("Platzi_ASP_NET_CORE.Models.Alumno", "Alumno")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platzi_ASP_NET_CORE.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Alumno", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Curso", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Platzi_ASP_NET_CORE.Models.Escuela", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
